#ifndef MINI_STATE_GENERATED_H
#define MINI_STATE_GENERATED_H

/* Generated by features/game-state/scripts/generate_state.py from features/game-state/tests/mini_state.schema.json. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "cJSON.h"
#include "game_save.h"

#define MINI_STATE_SCHEMA_ID "mini.state"
#define MINI_STATE_FRAGMENT_ID "mini"
#define MINI_STATE_VERSION 1
#define MINI_STATE_STRING_MAX 32

#define MINI_STATE_MODE_INDEX_DEFAULT MINI_STATE_MODE_OFF
#define MINI_STATE_LABEL_DEFAULT "hi"
#define MINI_STATE_TOTAL_DEFAULT 0LL
#define MINI_STATE_TOTAL_MIN 0LL
#define MINI_STATE_TOTAL_MAX 9000000000000000000LL
#define MINI_STATE_CELL_COUNT_DEFAULT 0LL
#define MINI_STATE_CELL_COUNT_MIN 0LL
#define MINI_STATE_CELL_COUNT_MAX 9000000000000000000LL
#define MINI_STATE_MAX_CELLS 8
#define MINI_STATE_MAX_ORDER 8

typedef enum MiniStateMode {
    MINI_STATE_MODE_OFF = 0,
    MINI_STATE_MODE_ON,
    MINI_STATE_MODE_COUNT,
} MiniStateMode;

typedef struct MiniCell {
    bool used;
    char key[MINI_STATE_STRING_MAX];
    char def_id[MINI_STATE_STRING_MAX];
    int64_t count;
} MiniCell;

typedef struct MiniState {
    int mode_index;
    char label[MINI_STATE_STRING_MAX];
    int64_t total;
    MiniCell cells[MINI_STATE_MAX_CELLS];
    char order[MINI_STATE_MAX_ORDER][MINI_STATE_STRING_MAX];
    int order_count;
} MiniState;

/* Instance owned by this fragment TU (the shared global-state monolith is gone).
   Feature LOGIC works with it directly or through its own API. */
extern MiniState mini_state;

const char *mini_state_mode_name(int value);

void   mini_state_init_defaults(MiniState *state);
bool   mini_state_validate(const MiniState *state, char *error, int error_cap);
cJSON *mini_state_schema_json(void);
cJSON *mini_state_to_json(const MiniState *state);
cJSON *mini_state_get_path_json(const MiniState *state, const char *path, char *error, int error_cap);
bool   mini_state_set_path_json(MiniState *state, const char *path, const cJSON *value, char *error, int error_cap);
bool   mini_state_patch_json(MiniState *state, const cJSON *values, char *error, int error_cap);
bool   mini_state_from_json(MiniState *state, const cJSON *json, char *error, int error_cap);

/* Generated descriptor — replaces the hand-written fragment adapter. */
extern const GameSaveFragment mini_state_fragment;

#endif
