#ifndef MINI_STATE_EVENTS_GEN_H
#define MINI_STATE_EVENTS_GEN_H

/* Generated by features/game-state/scripts/generate_state.py from features/game-state/tests/mini_state.schema.json. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "hash/nt_hash.h"    /* nt_hash64_t */
#include "game_event_desc.h" /* game_event_desc_t + field-type enum */

/* ---- mini.cell_spawned ---- */
typedef struct MiniEvCellSpawned {
    int64_t total;
    double rate; /* schema 'float' == C double (f64); event float != state float */
    nt_hash64_t kind;
    bool urgent;
    uint32_t label; /* byte offset -> inline NUL string (read via accessor) */
    uint32_t blob; /* byte offset -> inline bytes (read via accessor) */
    uint32_t blob_len; /* length of the inline bytes */
} MiniEvCellSpawned;

nt_hash64_t mini_ev_cell_spawned_type(void); /* nt_hash64_str("mini.cell_spawned"), cached */

const void *mini_emit_cell_spawned(int64_t total, double rate, nt_hash64_t kind, bool urgent, const char *label, const void *blob, uint32_t blob_len);

static inline const char *mini_ev_cell_spawned_label(const MiniEvCellSpawned *e) {
    return (const char *)e + e->label;
}
static inline const void *mini_ev_cell_spawned_blob(const MiniEvCellSpawned *e) {
    return (const uint8_t *)e + e->blob;
}
static inline uint32_t mini_ev_cell_spawned_blob_len(const MiniEvCellSpawned *e) {
    return e->blob_len;
}

extern const game_event_desc_t mini_ev_cell_spawned_desc;

/* ---- mini.ticked ---- */
typedef struct MiniEvTicked {
    int32_t count;
} MiniEvTicked;

nt_hash64_t mini_ev_ticked_type(void); /* nt_hash64_str("mini.ticked"), cached */

const void *mini_emit_ticked(int32_t count);

extern const game_event_desc_t mini_ev_ticked_desc;

/* ---- mini.paid ---- */
typedef struct MiniEvPaidCost {
    uint32_t def_id; /* byte offset -> inline NUL string (read via accessor) */
    int64_t amount;
    int64_t before;
} MiniEvPaidCost;

typedef struct MiniEvPaidCostIn {
    const char *def_id;
    int64_t amount;
    int64_t before;
} MiniEvPaidCostIn;

typedef struct MiniEvPaid {
    int32_t count;
    uint32_t reason; /* byte offset -> inline NUL string (read via accessor) */
    uint32_t cost; /* byte offset -> inline record array (read via accessor) */
    uint32_t cost_count; /* number of inline records */
} MiniEvPaid;

nt_hash64_t mini_ev_paid_type(void); /* nt_hash64_str("mini.paid"), cached */

const void *mini_emit_paid(int32_t count, const char *reason, const MiniEvPaidCostIn *cost, uint32_t cost_count);

static inline const char *mini_ev_paid_reason(const MiniEvPaid *e) {
    return (const char *)e + e->reason;
}
static inline uint32_t mini_ev_paid_cost_count(const MiniEvPaid *e) {
    return e->cost_count;
}
static inline const MiniEvPaidCost *mini_ev_paid_cost_at(const MiniEvPaid *e, uint32_t i) {
    return (const MiniEvPaidCost *)((const uint8_t *)e + e->cost) + i;
}
static inline const char *mini_ev_paid_cost_def_id(const MiniEvPaid *e, uint32_t i) {
    return (const char *)e + mini_ev_paid_cost_at(e, i)->def_id;
}

extern const game_event_desc_t mini_ev_paid_desc;

/* ---- fragment event table + label registration ---- */
extern const game_event_desc_t *const mini_ev_descs[];
extern const int mini_ev_desc_count;

void mini_ev_register(void); /* register debug labels; call once after nt_hash_init */

#endif /* MINI_STATE_EVENTS_GEN_H */
