#ifndef MINI_STATE_SCHEMA_GEN_H
#define MINI_STATE_SCHEMA_GEN_H

/* Generated by features/game-state/scripts/generate_state.py from features/game-state/tests/mini_state.schema.json. */
#define MINI_STATE_SCHEMA_JSON_CHUNKS \
    { \
    "{\"schema\":\"mini.state\",\"document\":\"mini\",\"fragment\":\"mini\",\"version\":1,\"schema_version\":2,\"string_max\":32,\"enums\":{\"Mode\":[\"off\",\"on\"]},\"types\":{\"Cell\":{\"kind\":\"object\",\"fields\":[{\"path\":\"def_id\",\"type\":\"string\",\"max_length\":15},{\"path\":\"count\",\"type\":\"i64\",\"default\":0,\"min\":0,\"max\":9000000000000000000}]}},\"fields\":[{\"path\":\"mode_index\",\"type\":\"enum\",\"enum\":\"Mode\",\"default\":\"off\"},{\"path\":\"label\",\"type\":\"string\",\"default\":\"hi\",\"max_length\":15},{\"path\":\"total\",\"type\":\"i64\",\"default\":0,\"min\":0,\"max\":9000000000000000000},{\"path\":\"cells\",\"type\":\"map<string,Cell>\",\"max_count\":8},{\"path\":\"order\",\"type\":\"list<string>\",\"max_count\":8}]}", \
    "" \
    }

#endif
