#include "mini_state.h"
#include "mini_state_schema.gen.h"
#include "game_state_json.h"

/* Generated by features/game-state/scripts/generate_state.py from features/game-state/tests/mini_state.schema.json. */

#include <stdlib.h>
#include <string.h>

static const char *const k_mode_names[MINI_STATE_MODE_COUNT] = {
    "off",
    "on",
};

const char *mini_state_mode_name(int value) {
    return (value >= 0 && value < MINI_STATE_MODE_COUNT) ? k_mode_names[value] : "unknown";
}

MiniState mini_state;   /* fragment instance (ownership lives here) */

static void cell_init_defaults(MiniCell *obj, const char *key) {
    memset(obj, 0, sizeof(*obj));
    obj->used = true;
    (void)gsj_copy_text(obj->key, sizeof(obj->key), key);
    obj->count = MINI_STATE_CELL_COUNT_DEFAULT;
}

static bool cell_validate(const MiniCell *obj, char *error, int error_cap) {
    if (!obj->used) { return true; }
    if (obj->key[0] == '\0') { gsj_set_error(error, error_cap, "object key is empty"); return false; }
    if (obj->def_id[0] == '\0') {
        gsj_set_error(error, error_cap, "def_id out of range");
        return false;
    }
    if (obj->count < MINI_STATE_CELL_COUNT_MIN || obj->count > MINI_STATE_CELL_COUNT_MAX) {
        gsj_set_error(error, error_cap, "count out of range");
        return false;
    }
    return true;
}

static cJSON *cell_to_json(const MiniCell *obj) {
    cJSON *json = cJSON_CreateObject();
    cJSON_AddStringToObject(json, "def_id", obj->def_id);
    gsj_add_i64(json, "count", obj->count);
    return json;
}

static cJSON *cell_get_field_json(const MiniCell *obj, const char *field, char *error, int error_cap) {
    if (!field || field[0] == '\0') { return cell_to_json(obj); }
    if (strcmp(field, "def_id") == 0) {
        return cJSON_CreateString(obj->def_id);
    }
    if (strcmp(field, "count") == 0) {
        return cJSON_CreateString(gsj_i64_to_string(obj->count, (char[21]){0}, 21));
    }
    gsj_set_error(error, error_cap, "unknown object field");
    return NULL;
}

static bool cell_set_field_json(MiniCell *obj, const char *field, const cJSON *value, char *error, int error_cap) {
    if (strcmp(field, "def_id") == 0) {
        if (!cJSON_IsString(value) || !gsj_copy_text(obj->def_id, sizeof(obj->def_id), value->valuestring)) { gsj_set_error(error, error_cap, "expected short string"); return false; }
        return true;
    }
    if (strcmp(field, "count") == 0) {
        if (!gsj_parse_i64_value(value, MINI_STATE_CELL_COUNT_MIN, MINI_STATE_CELL_COUNT_MAX, &obj->count, error, error_cap)) { return false; }
        return true;
    }
    gsj_set_error(error, error_cap, "unknown object field");
    return false;
}

static bool cell_from_json(MiniCell *obj, const cJSON *json, char *error, int error_cap) {
    if (!cJSON_IsObject(json)) { gsj_set_error(error, error_cap, "object must be json object"); return false; }
    if (!gsj_read_string(json, "def_id", obj->def_id, sizeof(obj->def_id), error, error_cap)) { return false; }
    if (!gsj_read_i64(json, "count", MINI_STATE_CELL_COUNT_MIN, MINI_STATE_CELL_COUNT_MAX, &obj->count, error, error_cap)) { return false; }
    return cell_validate(obj, error, error_cap);
}


static MiniCell *find_cells(MiniState *state, const char *key) {
    for (int i = 0; i < MINI_STATE_MAX_CELLS; i++) {
        if (state->cells[i].used && strcmp(state->cells[i].key, key) == 0) {
            return &state->cells[i];
        }
    }
    return NULL;
}

static const MiniCell *find_cells_const(const MiniState *state, const char *key) {
    for (int i = 0; i < MINI_STATE_MAX_CELLS; i++) {
        if (state->cells[i].used && strcmp(state->cells[i].key, key) == 0) {
            return &state->cells[i];
        }
    }
    return NULL;
}

static MiniCell *alloc_cells(MiniState *state, const char *key) {
    MiniCell *existing = find_cells(state, key);
    if (existing) { return existing; }
    for (int i = 0; i < MINI_STATE_MAX_CELLS; i++) {
        if (!state->cells[i].used) {
            cell_init_defaults(&state->cells[i], key);
            return state->cells[i].used ? &state->cells[i] : NULL;
        }
    }
    return NULL;
}

static cJSON *cells_to_json(const MiniState *state) {
    cJSON *json = cJSON_CreateObject();
    for (int i = 0; i < MINI_STATE_MAX_CELLS; i++) {
        if (state->cells[i].used) {
            cJSON_AddItemToObject(json, state->cells[i].key, cell_to_json(&state->cells[i]));
        }
    }
    return json;
}

static bool set_cells_from_json(MiniState *state, const cJSON *json, char *error, int error_cap) {
    if (!cJSON_IsObject(json)) { gsj_set_error(error, error_cap, "map must be object"); return false; }
    for (int i = 0; i < MINI_STATE_MAX_CELLS; i++) { memset(&state->cells[i], 0, sizeof(state->cells[i])); }
    const cJSON *child = NULL;
    cJSON_ArrayForEach(child, json) {
        if (!child->string) { continue; }
        MiniCell *obj = alloc_cells(state, child->string);
        if (!obj) { gsj_set_error(error, error_cap, "too many map entries or long key"); return false; }
        if (!cell_from_json(obj, child, error, error_cap)) { return false; }
    }
    return true;
}



static cJSON *order_to_json(const MiniState *state) {
    cJSON *json = cJSON_CreateArray();
    for (int i = 0; i < state->order_count; i++) {
        cJSON_AddItemToArray(json, cJSON_CreateString(state->order[i]));
    }
    return json;
}

static bool set_order_from_json(MiniState *state, const cJSON *json, char *error, int error_cap) {
    if (!cJSON_IsArray(json)) { gsj_set_error(error, error_cap, "list must be array"); return false; }
    int count = cJSON_GetArraySize((cJSON *)json);
    if (count > MINI_STATE_MAX_ORDER) { gsj_set_error(error, error_cap, "too many list entries"); return false; }
    state->order_count = 0;
    for (int i = 0; i < count; i++) {
        const cJSON *entry = cJSON_GetArrayItem((cJSON *)json, i);
        if (!cJSON_IsString(entry) || !gsj_copy_text(state->order[i], sizeof(state->order[i]), entry->valuestring)) {
            gsj_set_error(error, error_cap, "list entry must be short string");
            return false;
        }
        state->order_count++;
    }
    return true;
}


void mini_state_init_defaults(MiniState *state) {
    memset(state, 0, sizeof(*state));
    state->mode_index = MINI_STATE_MODE_INDEX_DEFAULT;
    (void)gsj_copy_text(state->label, sizeof(state->label), MINI_STATE_LABEL_DEFAULT);
    state->total = MINI_STATE_TOTAL_DEFAULT;
}

bool mini_state_validate(const MiniState *state, char *error, int error_cap) {
    if (!state) { gsj_set_error(error, error_cap, "state is null"); return false; }
    if (state->mode_index < 0 || state->mode_index >= MINI_STATE_MODE_COUNT) {
        gsj_set_error(error, error_cap, "mode_index out of range");
        return false;
    }
    if (state->label[0] == '\0') {
        gsj_set_error(error, error_cap, "label out of range");
        return false;
    }
    if (state->total < MINI_STATE_TOTAL_MIN || state->total > MINI_STATE_TOTAL_MAX) {
        gsj_set_error(error, error_cap, "total out of range");
        return false;
    }
    if (state->order_count < 0 || state->order_count > MINI_STATE_MAX_ORDER) {
        gsj_set_error(error, error_cap, "order count out of range");
        return false;
    }
    for (int i = 0; i < state->order_count; i++) {
        if (state->order[i][0] == '\0') {
            gsj_set_error(error, error_cap, "order contains empty id");
            return false;
        }
    }
    for (int i = 0; i < MINI_STATE_MAX_CELLS; i++) {
        if (state->cells[i].used && !cell_validate(&state->cells[i], error, error_cap)) {
            return false;
        }
    }
    return true;
}

cJSON *mini_state_schema_json(void) {
    const char *chunks[] = MINI_STATE_SCHEMA_JSON_CHUNKS;
    size_t len = 0;
    for (size_t i = 0; chunks[i][0] != '\0'; i++) { len += strlen(chunks[i]); }
    char *json = (char *)malloc(len + 1U);
    if (!json) { return cJSON_CreateObject(); }
    char *cursor = json;
    for (size_t i = 0; chunks[i][0] != '\0'; i++) {
        size_t chunk_len = strlen(chunks[i]);
        memcpy(cursor, chunks[i], chunk_len);
        cursor += chunk_len;
    }
    json[len] = '\0';
    cJSON *root = cJSON_Parse(json);
    free(json);
    return root ? root : cJSON_CreateObject();
}

cJSON *mini_state_to_json(const MiniState *state) {
    cJSON *root = cJSON_CreateObject();
    cJSON_AddNumberToObject(root, "mode_index", state->mode_index);
    cJSON_AddStringToObject(root, "mode", mini_state_mode_name(state->mode_index));
    cJSON_AddStringToObject(root, "label", state->label);
    gsj_add_i64(root, "total", state->total);
    cJSON_AddItemToObject(root, "cells", cells_to_json(state));
    cJSON_AddItemToObject(root, "order", order_to_json(state));
    return root;
}

cJSON *mini_state_get_path_json(const MiniState *state, const char *path, char *error, int error_cap) {
    if (!path || path[0] == '\0') { return mini_state_to_json(state); }
    if (strcmp(path, "mode_index") == 0) {
        return cJSON_CreateString(mini_state_mode_name(state->mode_index));
    }
    if (strcmp(path, "label") == 0) {
        return cJSON_CreateString(state->label);
    }
    if (strcmp(path, "total") == 0) {
        return cJSON_CreateString(gsj_i64_to_string(state->total, (char[21]){0}, 21));
    }
    if (strcmp(path, "order") == 0) {
        return order_to_json(state);
    }
    if (strcmp(path, "cells") == 0) {
        return cells_to_json(state);
    }
    if (strncmp(path, "cells.", 6) == 0) {
        const char *key = path + 6;
        const char *field = strchr(key, '.');
        char map_key[MINI_STATE_STRING_MAX];
        if (field) {
            size_t len = (size_t)(field - key);
            if (len == 0 || len >= sizeof(map_key)) { gsj_set_error(error, error_cap, "bad map key"); return NULL; }
            memcpy(map_key, key, len);
            map_key[len] = '\0';
            field++;
        } else if (!gsj_copy_text(map_key, sizeof(map_key), key)) {
            gsj_set_error(error, error_cap, "bad map key");
            return NULL;
        }
        const MiniCell *obj = find_cells_const(state, map_key);
        if (!obj) { gsj_set_error(error, error_cap, "unknown map key"); return NULL; }
        return cell_get_field_json(obj, field, error, error_cap);
    }
    gsj_set_error(error, error_cap, "unknown state path");
    return NULL;
}

bool mini_state_set_path_json(MiniState *state, const char *path, const cJSON *value, char *error, int error_cap) {
    if (!state || !path || !path[0] || !value) { gsj_set_error(error, error_cap, "path and value are required"); return false; }
    if (strcmp(path, "mode_index") == 0) {
        if (!gsj_parse_enum_value(value, k_mode_names, MINI_STATE_MODE_COUNT, &state->mode_index, error, error_cap)) { return false; }
        return true;
    }
    if (strcmp(path, "label") == 0) {
        if (!cJSON_IsString(value) || !gsj_copy_text(state->label, sizeof(state->label), value->valuestring)) { gsj_set_error(error, error_cap, "expected short string"); return false; }
        return true;
    }
    if (strcmp(path, "total") == 0) {
        if (!gsj_parse_i64_value(value, MINI_STATE_TOTAL_MIN, MINI_STATE_TOTAL_MAX, &state->total, error, error_cap)) { return false; }
        return true;
    }
    if (strcmp(path, "order") == 0) {
        return set_order_from_json(state, value, error, error_cap);
    }
    if (strcmp(path, "cells") == 0) {
        return set_cells_from_json(state, value, error, error_cap);
    }
    if (strncmp(path, "cells.", 6) == 0) {
        const char *key = path + 6;
        const char *field = strchr(key, '.');
        char map_key[MINI_STATE_STRING_MAX];
        if (field) {
            size_t len = (size_t)(field - key);
            if (len == 0 || len >= sizeof(map_key)) { gsj_set_error(error, error_cap, "bad map key"); return false; }
            memcpy(map_key, key, len);
            map_key[len] = '\0';
            field++;
        } else if (!gsj_copy_text(map_key, sizeof(map_key), key)) {
            gsj_set_error(error, error_cap, "bad map key");
            return false;
        }
        MiniCell *obj = alloc_cells(state, map_key);
        if (!obj) { gsj_set_error(error, error_cap, "too many map entries or long key"); return false; }
        return field ? cell_set_field_json(obj, field, value, error, error_cap) : cell_from_json(obj, value, error, error_cap);
    }
    gsj_set_error(error, error_cap, "unknown state path");
    return false;
}

bool mini_state_patch_json(MiniState *state, const cJSON *values, char *error, int error_cap) {
    if (!cJSON_IsObject(values)) { gsj_set_error(error, error_cap, "values must be an object"); return false; }
    MiniState next = *state;
    const cJSON *item = NULL;
    cJSON_ArrayForEach(item, values) {
        if (!item->string || !mini_state_set_path_json(&next, item->string, item, error, error_cap)) { return false; }
    }
    if (!mini_state_validate(&next, error, error_cap)) { return false; }
    *state = next;
    return true;
}

bool mini_state_from_json(MiniState *state, const cJSON *json, char *error, int error_cap) {
    if (!cJSON_IsObject(json)) { gsj_set_error(error, error_cap, "state json must be object"); return false; }
    MiniState next;
    mini_state_init_defaults(&next);
    if (!gsj_read_enum(json, "mode_index", k_mode_names, MINI_STATE_MODE_COUNT, &(&next)->mode_index, error, error_cap)) { return false; }
    if (!gsj_read_string(json, "label", (&next)->label, sizeof((&next)->label), error, error_cap)) { return false; }
    if (!gsj_read_i64(json, "total", MINI_STATE_TOTAL_MIN, MINI_STATE_TOTAL_MAX, &(&next)->total, error, error_cap)) { return false; }
    const cJSON *cells_json = gsj_object_item(json, "cells");
    if (cells_json && !set_cells_from_json(&next, cells_json, error, error_cap)) {
        return false;
    }
    const cJSON *order_json = gsj_object_item(json, "order");
    if (order_json && !set_order_from_json(&next, order_json, error, error_cap)) {
        return false;
    }
    if (!mini_state_validate(&next, error, error_cap)) { return false; }
    *state = next;
    return true;
}

static void   frag_reset(void)                                             { mini_state_init_defaults(&mini_state); }
static cJSON *frag_to_json(void)                                           { return mini_state_to_json(&mini_state); }
static bool   frag_from_json(const cJSON *j, char *e, int c)               { return mini_state_from_json(&mini_state, j, e, c); }
static cJSON *frag_get_path(const char *s, char *e, int c)                 { return mini_state_get_path_json(&mini_state, s, e, c); }
static bool   frag_set_path(const char *s, const cJSON *v, char *e, int c) { return mini_state_set_path_json(&mini_state, s, v, e, c); }
static cJSON *frag_schema(void)                                            { return mini_state_schema_json(); }

const GameSaveFragment mini_state_fragment = {
    .id            = MINI_STATE_FRAGMENT_ID,
    .version       = MINI_STATE_VERSION,
    .steps         = NULL,
    .reset         = frag_reset,
    .on_new_game   = NULL,
    .to_json       = frag_to_json,
    .from_json     = frag_from_json,
    .reconcile     = NULL,
    .get_path_json = frag_get_path,
    .set_path_json = frag_set_path,
    .schema_json   = frag_schema,
};
