#include "mini_state_events.gen.h"

/* Generated by features/game-state/scripts/generate_state.py from features/game-state/tests/mini_state.schema.json. */

#include <stddef.h> /* offsetof, max_align_t */
#include <string.h> /* memcpy, memset, strlen */

#include "core/nt_assert.h"
#include "game_events.h" /* game_event_emit, game_event_register_type_name */
#include "log/nt_log.h"  /* nt_log_warn on staging overflow (release-visible) */

_Static_assert(_Alignof(MiniEvCellSpawned) <= _Alignof(max_align_t),
               "MiniEvCellSpawned over-aligned for game_event_emit");
_Static_assert(_Alignof(MiniEvTicked) <= _Alignof(max_align_t),
               "MiniEvTicked over-aligned for game_event_emit");

/* ---- mini.cell_spawned ---- */
nt_hash64_t mini_ev_cell_spawned_type(void) {
    static nt_hash64_t h;
    if (!h.value) { h = nt_hash64_str("mini.cell_spawned"); }
    return h;
}

const void *mini_emit_cell_spawned(int64_t total, double rate, nt_hash64_t kind, bool urgent, const char *label, const void *blob, uint32_t blob_len) {
    union {
        MiniEvCellSpawned ev;
        uint8_t bytes[GAME_EVENT_EMIT_MAX];
    } u;
    memset(&u, 0, sizeof(u.ev)); /* deterministic struct padding; strings written below */
    u.ev.total = total;
    u.ev.rate = rate;
    u.ev.kind = kind;
    u.ev.urgent = urgent;

    uint32_t off = (uint32_t)sizeof(u.ev);
    const char *label_s = label ? label : "";
    size_t label_n = strlen(label_s) + 1u; /* incl. NUL */
    if ((size_t)off + label_n + (size_t)blob_len > sizeof(u.bytes)) {
        NT_ASSERT(0 && "mini_emit_cell_spawned payload exceeds GAME_EVENT_EMIT_MAX");
        nt_log_warn("mini_emit_cell_spawned: payload exceeds GAME_EVENT_EMIT_MAX (%u B) -> dropped", (unsigned)GAME_EVENT_EMIT_MAX);
        return NULL; /* release: warned drop (no dropped-counter -- E1's counter is private/frozen) */
    }
    u.ev.label = off;
    memcpy(u.bytes + off, label_s, label_n);
    off += (uint32_t)label_n;

    u.ev.blob = off;
    u.ev.blob_len = blob_len;
    if (blob_len != 0u && blob != NULL) { memcpy(u.bytes + off, blob, blob_len); }
    off += blob_len;
    return game_event_emit(mini_ev_cell_spawned_type(), &u, off, _Alignof(MiniEvCellSpawned));
}

static const game_event_field_t mini_ev_cell_spawned_fields[] = {
    { "total", GAME_EVENT_FT_I64, (uint32_t)offsetof(MiniEvCellSpawned, total), 0u },
    { "rate", GAME_EVENT_FT_FLOAT, (uint32_t)offsetof(MiniEvCellSpawned, rate), 0u },
    { "kind", GAME_EVENT_FT_HASH, (uint32_t)offsetof(MiniEvCellSpawned, kind), 0u },
    { "urgent", GAME_EVENT_FT_BOOL, (uint32_t)offsetof(MiniEvCellSpawned, urgent), 0u },
    { "label", GAME_EVENT_FT_STRING, (uint32_t)offsetof(MiniEvCellSpawned, label), 0u },
    { "blob", GAME_EVENT_FT_BYTES, (uint32_t)offsetof(MiniEvCellSpawned, blob), (uint32_t)offsetof(MiniEvCellSpawned, blob_len) },
};
const game_event_desc_t mini_ev_cell_spawned_desc = {
    "mini.cell_spawned",
    (uint32_t)sizeof(MiniEvCellSpawned),
    mini_ev_cell_spawned_fields,
    (int)(sizeof(mini_ev_cell_spawned_fields) / sizeof(mini_ev_cell_spawned_fields[0])),
};

/* ---- mini.ticked ---- */
nt_hash64_t mini_ev_ticked_type(void) {
    static nt_hash64_t h;
    if (!h.value) { h = nt_hash64_str("mini.ticked"); }
    return h;
}

const void *mini_emit_ticked(int32_t count) {
    MiniEvTicked ev;
    memset(&ev, 0, sizeof(ev));
    ev.count = count;
    return game_event_emit(mini_ev_ticked_type(), &ev, (uint32_t)sizeof(ev), _Alignof(MiniEvTicked));
}

static const game_event_field_t mini_ev_ticked_fields[] = {
    { "count", GAME_EVENT_FT_INT, (uint32_t)offsetof(MiniEvTicked, count), 0u },
};
const game_event_desc_t mini_ev_ticked_desc = {
    "mini.ticked",
    (uint32_t)sizeof(MiniEvTicked),
    mini_ev_ticked_fields,
    (int)(sizeof(mini_ev_ticked_fields) / sizeof(mini_ev_ticked_fields[0])),
};

/* ---- fragment event table ---- */
const game_event_desc_t *const mini_ev_descs[] = {
    &mini_ev_cell_spawned_desc,
    &mini_ev_ticked_desc,
};
const int mini_ev_desc_count = 2;

void mini_ev_register(void) {
    game_event_register_type_name(mini_ev_cell_spawned_type(), "mini.cell_spawned");
    game_event_register_type_name(mini_ev_ticked_type(), "mini.ticked");
}
