#include "game_state_events.gen.h"

/* Generated by features/game-state/scripts/generate_state.py from state/game_state.schema.json. */

#include <stddef.h> /* offsetof, max_align_t */
#include <string.h> /* memcpy, memset, strlen */

#include "core/nt_assert.h"
#include "game_events.h" /* game_event_emit, game_event_register_type_name */
#include "log/nt_log.h"  /* nt_log_warn on staging overflow (release-visible) */

_Static_assert(_Alignof(GameEvShapeChanged) <= _Alignof(max_align_t),
               "GameEvShapeChanged over-aligned for game_event_emit");

/* ---- game.shape_changed ---- */
nt_hash64_t game_ev_shape_changed_type(void) {
    static nt_hash64_t h;
    if (!h.value) { h = nt_hash64_str("game.shape_changed"); }
    return h;
}

const void *game_emit_shape_changed(int32_t from_index, int32_t to_index, const char *note) {
    union {
        GameEvShapeChanged ev;
        uint8_t bytes[GAME_EVENT_EMIT_MAX];
    } u;
    memset(&u, 0, sizeof(u.ev)); /* deterministic struct padding; strings written below */
    u.ev.from_index = from_index;
    u.ev.to_index = to_index;

    uint32_t off = (uint32_t)sizeof(u.ev);
    const char *note_s = note ? note : "";
    size_t note_n = strlen(note_s) + 1u; /* incl. NUL */
    if ((size_t)off + note_n > sizeof(u.bytes)) {
        NT_ASSERT(0 && "game_emit_shape_changed payload exceeds GAME_EVENT_EMIT_MAX");
        nt_log_warn("game_emit_shape_changed: payload exceeds GAME_EVENT_EMIT_MAX (%u B) -> dropped", (unsigned)GAME_EVENT_EMIT_MAX);
        return NULL; /* release: warned drop (no dropped-counter -- E1's counter is private/frozen) */
    }
    u.ev.note = off;
    memcpy(u.bytes + off, note_s, note_n);
    off += (uint32_t)note_n;
    return game_event_emit(game_ev_shape_changed_type(), &u, off, _Alignof(GameEvShapeChanged));
}

static const game_event_field_t game_ev_shape_changed_fields[] = {
    { "from_index", GAME_EVENT_FT_INT, (uint32_t)offsetof(GameEvShapeChanged, from_index), 0u },
    { "to_index", GAME_EVENT_FT_INT, (uint32_t)offsetof(GameEvShapeChanged, to_index), 0u },
    { "note", GAME_EVENT_FT_STRING, (uint32_t)offsetof(GameEvShapeChanged, note), 0u },
};
const game_event_desc_t game_ev_shape_changed_desc = {
    "game.shape_changed",
    (uint32_t)sizeof(GameEvShapeChanged),
    game_ev_shape_changed_fields,
    (int)(sizeof(game_ev_shape_changed_fields) / sizeof(game_ev_shape_changed_fields[0])),
};

/* ---- fragment event table ---- */
const game_event_desc_t *const game_ev_descs[] = {
    &game_ev_shape_changed_desc,
};
const int game_ev_desc_count = 1;

void game_ev_register(void) {
    game_event_register_type_name(game_ev_shape_changed_type(), "game.shape_changed");
}
