#include "game_state.h"
#include "game_state_schema.gen.h"
#include "game_state_json.h"

/* Generated by features/game-state/scripts/generate_state.py from state/game_state.schema.json. */

#include <stdlib.h>
#include <string.h>
#include <math.h>

static const char *const k_shape_names[GAME_STATE_SHAPE_COUNT] = {
    "cube",
    "sphere",
    "cylinder",
    "capsule",
};

static const char *const k_render_mode_names[GAME_STATE_RENDER_MODE_COUNT] = {
    "solid_wire",
    "solid",
    "wire",
};

const char *game_state_shape_name(int value) {
    return (value >= 0 && value < GAME_STATE_SHAPE_COUNT) ? k_shape_names[value] : "unknown";
}

const char *game_state_render_mode_name(int value) {
    return (value >= 0 && value < GAME_STATE_RENDER_MODE_COUNT) ? k_render_mode_names[value] : "unknown";
}

GameState game_state;   /* fragment instance (ownership lives here) */







void game_state_init_defaults(GameState *state) {
    memset(state, 0, sizeof(*state));
    state->shape_index = GAME_STATE_SHAPE_INDEX_DEFAULT;
    state->render_mode_index = GAME_STATE_RENDER_MODE_INDEX_DEFAULT;
    state->camera_distance = GAME_STATE_CAMERA_DISTANCE_DEFAULT;
    state->test_ui_clicks = GAME_STATE_TEST_UI_CLICKS_DEFAULT;
    (void)gsj_copy_text(state->test_label_text, sizeof(state->test_label_text), GAME_STATE_TEST_LABEL_TEXT_DEFAULT);
    (void)gsj_copy_text(state->test_button_text, sizeof(state->test_button_text), GAME_STATE_TEST_BUTTON_TEXT_DEFAULT);
    state->tutorial_done = GAME_STATE_TUTORIAL_DONE_DEFAULT;
    state->inventory_container_id = GAME_STATE_INVENTORY_CONTAINER_ID_DEFAULT;
    state->wallet_container_id = GAME_STATE_WALLET_CONTAINER_ID_DEFAULT;
}

bool game_state_validate(const GameState *state, char *error, int error_cap) {
    if (!state) { gsj_set_error(error, error_cap, "state is null"); return false; }
    if (state->shape_index < 0 || state->shape_index >= GAME_STATE_SHAPE_COUNT) {
        gsj_set_error(error, error_cap, "shape_index out of range");
        return false;
    }
    if (state->render_mode_index < 0 || state->render_mode_index >= GAME_STATE_RENDER_MODE_COUNT) {
        gsj_set_error(error, error_cap, "render_mode_index out of range");
        return false;
    }
    if (state->camera_distance < GAME_STATE_CAMERA_DISTANCE_MIN || state->camera_distance > GAME_STATE_CAMERA_DISTANCE_MAX) {
        gsj_set_error(error, error_cap, "camera_distance out of range");
        return false;
    }
    if (state->test_ui_clicks < GAME_STATE_TEST_UI_CLICKS_MIN || state->test_ui_clicks > GAME_STATE_TEST_UI_CLICKS_MAX) {
        gsj_set_error(error, error_cap, "test_ui_clicks out of range");
        return false;
    }
    if (state->test_label_text[0] == '\0') {
        gsj_set_error(error, error_cap, "test_label_text out of range");
        return false;
    }
    if (state->test_button_text[0] == '\0') {
        gsj_set_error(error, error_cap, "test_button_text out of range");
        return false;
    }
    if (state->inventory_container_id < GAME_STATE_INVENTORY_CONTAINER_ID_MIN || state->inventory_container_id > GAME_STATE_INVENTORY_CONTAINER_ID_MAX) {
        gsj_set_error(error, error_cap, "inventory_container_id out of range");
        return false;
    }
    if (state->wallet_container_id < GAME_STATE_WALLET_CONTAINER_ID_MIN || state->wallet_container_id > GAME_STATE_WALLET_CONTAINER_ID_MAX) {
        gsj_set_error(error, error_cap, "wallet_container_id out of range");
        return false;
    }
    return true;
}

cJSON *game_state_schema_json(void) {
    const char *chunks[] = GAME_STATE_SCHEMA_JSON_CHUNKS;
    size_t len = 0;
    for (size_t i = 0; chunks[i][0] != '\0'; i++) { len += strlen(chunks[i]); }
    char *json = (char *)malloc(len + 1U);
    if (!json) { return cJSON_CreateObject(); }
    char *cursor = json;
    for (size_t i = 0; chunks[i][0] != '\0'; i++) {
        size_t chunk_len = strlen(chunks[i]);
        memcpy(cursor, chunks[i], chunk_len);
        cursor += chunk_len;
    }
    json[len] = '\0';
    cJSON *root = cJSON_Parse(json);
    free(json);
    return root ? root : cJSON_CreateObject();
}

cJSON *game_state_to_json(const GameState *state) {
    cJSON *root = cJSON_CreateObject();
    cJSON_AddNumberToObject(root, "shape_index", state->shape_index);
    cJSON_AddStringToObject(root, "shape", game_state_shape_name(state->shape_index));
    cJSON_AddNumberToObject(root, "render_mode_index", state->render_mode_index);
    cJSON_AddStringToObject(root, "render_mode", game_state_render_mode_name(state->render_mode_index));
    cJSON_AddNumberToObject(root, "camera_distance", (double)state->camera_distance);
    cJSON_AddNumberToObject(root, "test_ui_clicks", state->test_ui_clicks);
    cJSON_AddStringToObject(root, "test_label_text", state->test_label_text);
    cJSON_AddStringToObject(root, "test_button_text", state->test_button_text);
    cJSON *tutorial = cJSON_AddObjectToObject(root, "tutorial");
    cJSON_AddBoolToObject(tutorial, "done", state->tutorial_done);
    cJSON_AddNumberToObject(root, "inventory_container_id", (double)state->inventory_container_id);
    cJSON_AddNumberToObject(root, "wallet_container_id", (double)state->wallet_container_id);
    return root;
}

bool game_state_write_snapshot(const GameState *state, game_save_writer_t *writer) {
    if (!state || !writer) { return false; }
    if (!game_save_writer_key(writer, "shape_index") || !game_save_writer_number(writer, state->shape_index)) { return false; }
    if (!game_save_writer_key(writer, "shape") || !game_save_writer_string(writer, game_state_shape_name(state->shape_index))) { return false; }
    if (!game_save_writer_key(writer, "render_mode_index") || !game_save_writer_number(writer, state->render_mode_index)) { return false; }
    if (!game_save_writer_key(writer, "render_mode") || !game_save_writer_string(writer, game_state_render_mode_name(state->render_mode_index))) { return false; }
    if (!game_save_writer_key(writer, "camera_distance") || !game_save_writer_number(writer, (double)state->camera_distance)) { return false; }
    if (!game_save_writer_key(writer, "test_ui_clicks") || !game_save_writer_number(writer, (double)state->test_ui_clicks)) { return false; }
    if (!game_save_writer_key(writer, "test_label_text") || !game_save_writer_string(writer, state->test_label_text)) { return false; }
    if (!game_save_writer_key(writer, "test_button_text") || !game_save_writer_string(writer, state->test_button_text)) { return false; }
    if (!game_save_writer_key(writer, "tutorial") || !game_save_writer_begin_object(writer)) { return false; }
    if (!game_save_writer_key(writer, "done") || !game_save_writer_bool(writer, state->tutorial_done)) { return false; }
    if (!game_save_writer_end_object(writer)) { return false; }
    if (!game_save_writer_key(writer, "inventory_container_id") || !game_save_writer_number(writer, (double)state->inventory_container_id)) { return false; }
    if (!game_save_writer_key(writer, "wallet_container_id") || !game_save_writer_number(writer, (double)state->wallet_container_id)) { return false; }
    return game_save_writer_ok(writer);
}

bool game_state_write_text(const GameState *state, game_save_text_writer_t *writer) {
    if (!state || !writer) { return false; }
    if (!game_save_text_write_string(writer, "shape_index", game_state_shape_name(state->shape_index))) { return false; }
    if (!game_save_text_write_string(writer, "render_mode_index", game_state_render_mode_name(state->render_mode_index))) { return false; }
    if (!game_save_text_write_number(writer, "camera_distance", (double)state->camera_distance)) { return false; }
    if (!game_save_text_write_i64(writer, "test_ui_clicks", (int64_t)state->test_ui_clicks)) { return false; }
    if (!game_save_text_write_string(writer, "test_label_text", state->test_label_text)) { return false; }
    if (!game_save_text_write_string(writer, "test_button_text", state->test_button_text)) { return false; }
    if (!game_save_text_write_bool(writer, "tutorial.done", state->tutorial_done)) { return false; }
    if (!game_save_text_write_i64(writer, "inventory_container_id", (int64_t)state->inventory_container_id)) { return false; }
    if (!game_save_text_write_i64(writer, "wallet_container_id", (int64_t)state->wallet_container_id)) { return false; }
    return game_save_text_writer_ok(writer);
}

bool game_state_from_text(GameState *state, const char *text, size_t size, char *error, int error_cap) {
    if (!state || !text) { gsj_set_error(error, error_cap, "text state is null"); return false; }
    GameState next;
    game_state_init_defaults(&next);
    bool seen[9] = {0};
    const size_t error_size = error_cap > 0 ? (size_t)error_cap : 0U;
    game_save_text_reader_t reader;
    game_save_text_fragment_reader_init(&reader, text, size, 1U);
    for (;;) {
        game_save_text_record_t record;
        game_save_text_result_t result = game_save_text_reader_next(&reader, &record, error, error_size);
        if (result == GAME_SAVE_TEXT_DONE) { break; }
        if (result == GAME_SAVE_TEXT_ERROR) { return false; }
        if (game_save_text_record_key_is(&record, "shape_index")) {
            if (seen[0]) { gsj_set_error(error, error_cap, "duplicate field"); return false; }
            seen[0] = true;
            char value[GAME_STATE_STRING_MAX];
            if (!game_save_text_record_string(&record, value, sizeof value, error, error_size)) { return false; }
            bool matched = false;
            for (int i = 0; i < GAME_STATE_SHAPE_COUNT; i++) {
                if (strcmp(value, k_shape_names[i]) == 0) { next.shape_index = i; matched = true; break; }
            }
            if (!matched) { gsj_set_error(error, error_cap, "enum value out of range"); return false; }
            continue;
        }
        if (game_save_text_record_key_is(&record, "render_mode_index")) {
            if (seen[1]) { gsj_set_error(error, error_cap, "duplicate field"); return false; }
            seen[1] = true;
            char value[GAME_STATE_STRING_MAX];
            if (!game_save_text_record_string(&record, value, sizeof value, error, error_size)) { return false; }
            bool matched = false;
            for (int i = 0; i < GAME_STATE_RENDER_MODE_COUNT; i++) {
                if (strcmp(value, k_render_mode_names[i]) == 0) { next.render_mode_index = i; matched = true; break; }
            }
            if (!matched) { gsj_set_error(error, error_cap, "enum value out of range"); return false; }
            continue;
        }
        if (game_save_text_record_key_is(&record, "camera_distance")) {
            if (seen[2]) { gsj_set_error(error, error_cap, "duplicate field"); return false; }
            seen[2] = true;
            double value = 0.0;
            if (!game_save_text_record_number(&record, (double)GAME_STATE_CAMERA_DISTANCE_MIN, (double)GAME_STATE_CAMERA_DISTANCE_MAX, &value, error, error_size)) { return false; }
            next.camera_distance = (float)value;
            continue;
        }
        if (game_save_text_record_key_is(&record, "test_ui_clicks")) {
            if (seen[3]) { gsj_set_error(error, error_cap, "duplicate field"); return false; }
            seen[3] = true;
            int64_t value = 0;
            if (!game_save_text_record_i64(&record, GAME_STATE_TEST_UI_CLICKS_MIN, GAME_STATE_TEST_UI_CLICKS_MAX, &value, error, error_size)) { return false; }
            next.test_ui_clicks = (int)value;
            continue;
        }
        if (game_save_text_record_key_is(&record, "test_label_text")) {
            if (seen[4]) { gsj_set_error(error, error_cap, "duplicate field"); return false; }
            seen[4] = true;
            if (!game_save_text_record_string(&record, next.test_label_text, sizeof next.test_label_text, error, error_size)) { return false; }
            continue;
        }
        if (game_save_text_record_key_is(&record, "test_button_text")) {
            if (seen[5]) { gsj_set_error(error, error_cap, "duplicate field"); return false; }
            seen[5] = true;
            if (!game_save_text_record_string(&record, next.test_button_text, sizeof next.test_button_text, error, error_size)) { return false; }
            continue;
        }
        if (game_save_text_record_key_is(&record, "tutorial.done")) {
            if (seen[6]) { gsj_set_error(error, error_cap, "duplicate field"); return false; }
            seen[6] = true;
            if (!game_save_text_record_bool(&record, &next.tutorial_done, error, error_size)) { return false; }
            continue;
        }
        if (game_save_text_record_key_is(&record, "inventory_container_id")) {
            if (seen[7]) { gsj_set_error(error, error_cap, "duplicate field"); return false; }
            seen[7] = true;
            int64_t value = 0;
            if (!game_save_text_record_i64(&record, (int64_t)GAME_STATE_INVENTORY_CONTAINER_ID_MIN, (int64_t)GAME_STATE_INVENTORY_CONTAINER_ID_MAX, &value, error, error_size)) { return false; }
            next.inventory_container_id = (uint32_t)value;
            continue;
        }
        if (game_save_text_record_key_is(&record, "wallet_container_id")) {
            if (seen[8]) { gsj_set_error(error, error_cap, "duplicate field"); return false; }
            seen[8] = true;
            int64_t value = 0;
            if (!game_save_text_record_i64(&record, (int64_t)GAME_STATE_WALLET_CONTAINER_ID_MIN, (int64_t)GAME_STATE_WALLET_CONTAINER_ID_MAX, &value, error, error_size)) { return false; }
            next.wallet_container_id = (uint32_t)value;
            continue;
        }
    }
    if (!game_state_validate(&next, error, error_cap)) { return false; }
    *state = next;
    return true;
}

cJSON *game_state_get_path_json(const GameState *state, const char *path, char *error, int error_cap) {
    if (!path || path[0] == '\0') { return game_state_to_json(state); }
    if (strcmp(path, "shape_index") == 0) {
        return cJSON_CreateString(game_state_shape_name(state->shape_index));
    }
    if (strcmp(path, "render_mode_index") == 0) {
        return cJSON_CreateString(game_state_render_mode_name(state->render_mode_index));
    }
    if (strcmp(path, "camera_distance") == 0) {
        return cJSON_CreateNumber((double)state->camera_distance);
    }
    if (strcmp(path, "test_ui_clicks") == 0) {
        return cJSON_CreateNumber(state->test_ui_clicks);
    }
    if (strcmp(path, "test_label_text") == 0) {
        return cJSON_CreateString(state->test_label_text);
    }
    if (strcmp(path, "test_button_text") == 0) {
        return cJSON_CreateString(state->test_button_text);
    }
    if (strcmp(path, "tutorial.done") == 0) {
        return cJSON_CreateBool(state->tutorial_done);
    }
    if (strcmp(path, "inventory_container_id") == 0) {
        return cJSON_CreateNumber((double)state->inventory_container_id);
    }
    if (strcmp(path, "wallet_container_id") == 0) {
        return cJSON_CreateNumber((double)state->wallet_container_id);
    }
    gsj_set_error(error, error_cap, "unknown state path");
    return NULL;
}

bool game_state_set_path_json(GameState *state, const char *path, const cJSON *value, char *error, int error_cap) {
    if (!state || !path || !path[0] || !value) { gsj_set_error(error, error_cap, "path and value are required"); return false; }
    if (strcmp(path, "shape_index") == 0) {
        if (!gsj_parse_enum_value(value, k_shape_names, GAME_STATE_SHAPE_COUNT, &state->shape_index, error, error_cap)) { return false; }
        return true;
    }
    if (strcmp(path, "render_mode_index") == 0) {
        if (!gsj_parse_enum_value(value, k_render_mode_names, GAME_STATE_RENDER_MODE_COUNT, &state->render_mode_index, error, error_cap)) { return false; }
        return true;
    }
    if (strcmp(path, "camera_distance") == 0) {
        if (!cJSON_IsNumber(value)) { gsj_set_error(error, error_cap, "expected number"); return false; }
        double number = value->valuedouble;
        if (!isfinite(number) || number < (double)GAME_STATE_CAMERA_DISTANCE_MIN || number > (double)GAME_STATE_CAMERA_DISTANCE_MAX) { gsj_set_error(error, error_cap, "number out of range"); return false; }
        float parsed = (float)number;
        state->camera_distance = parsed;
        return true;
    }
    if (strcmp(path, "test_ui_clicks") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_TEST_UI_CLICKS_MIN, GAME_STATE_TEST_UI_CLICKS_MAX, &parsed, error, error_cap)) { return false; }
        state->test_ui_clicks = parsed;
        return true;
    }
    if (strcmp(path, "test_label_text") == 0) {
        if (!cJSON_IsString(value) || !gsj_copy_text(state->test_label_text, sizeof(state->test_label_text), value->valuestring)) { gsj_set_error(error, error_cap, "expected short string"); return false; }
        return true;
    }
    if (strcmp(path, "test_button_text") == 0) {
        if (!cJSON_IsString(value) || !gsj_copy_text(state->test_button_text, sizeof(state->test_button_text), value->valuestring)) { gsj_set_error(error, error_cap, "expected short string"); return false; }
        return true;
    }
    if (strcmp(path, "tutorial.done") == 0) {
        if (!cJSON_IsBool(value)) { gsj_set_error(error, error_cap, "expected bool"); return false; }
        state->tutorial_done = cJSON_IsTrue(value);
        return true;
    }
    if (strcmp(path, "inventory_container_id") == 0) {
        gsj_set_error(error, error_cap, "state path is read-only");
        return false;
    }
    if (strcmp(path, "wallet_container_id") == 0) {
        gsj_set_error(error, error_cap, "state path is read-only");
        return false;
    }
    gsj_set_error(error, error_cap, "unknown state path");
    return false;
}

bool game_state_patch_json(GameState *state, const cJSON *values, char *error, int error_cap) {
    if (!cJSON_IsObject(values)) { gsj_set_error(error, error_cap, "values must be an object"); return false; }
    GameState *next = (GameState *)malloc(sizeof *next);
    if (!next) { gsj_set_error(error, error_cap, "failed to allocate staged state"); return false; }
    *next = *state;
    const cJSON *item = NULL;
    cJSON_ArrayForEach(item, values) {
        if (!item->string || !game_state_set_path_json(next, item->string, item, error, error_cap)) { free(next); return false; }
    }
    if (!game_state_validate(next, error, error_cap)) { free(next); return false; }
    *state = *next;
    free(next);
    return true;
}

bool game_state_from_json(GameState *state, const cJSON *json, char *error, int error_cap) {
    if (!cJSON_IsObject(json)) { gsj_set_error(error, error_cap, "state json must be object"); return false; }
    GameState *next = (GameState *)malloc(sizeof *next);
    if (!next) { gsj_set_error(error, error_cap, "failed to allocate staged state"); return false; }
    game_state_init_defaults(next);
    if (!gsj_read_enum(json, "shape_index", k_shape_names, GAME_STATE_SHAPE_COUNT, &next->shape_index, error, error_cap)) { free(next); return false; }
    if (!gsj_read_enum(json, "render_mode_index", k_render_mode_names, GAME_STATE_RENDER_MODE_COUNT, &next->render_mode_index, error, error_cap)) { free(next); return false; }
    if (!gsj_read_float_range(json, "camera_distance", GAME_STATE_CAMERA_DISTANCE_MIN, GAME_STATE_CAMERA_DISTANCE_MAX, &next->camera_distance, error, error_cap)) { free(next); return false; }
    if (!gsj_read_int_range(json, "test_ui_clicks", GAME_STATE_TEST_UI_CLICKS_MIN, GAME_STATE_TEST_UI_CLICKS_MAX, &next->test_ui_clicks, error, error_cap)) { free(next); return false; }
    if (!gsj_read_string(json, "test_label_text", next->test_label_text, sizeof(next->test_label_text), error, error_cap)) { free(next); return false; }
    if (!gsj_read_string(json, "test_button_text", next->test_button_text, sizeof(next->test_button_text), error, error_cap)) { free(next); return false; }
    const cJSON *tutorial = gsj_object_item(json, "tutorial");
    if (!gsj_read_bool(tutorial, "done", &next->tutorial_done, error, error_cap)) { free(next); return false; }
    if (!gsj_read_u32(json, "inventory_container_id", GAME_STATE_INVENTORY_CONTAINER_ID_MIN, GAME_STATE_INVENTORY_CONTAINER_ID_MAX, &next->inventory_container_id, error, error_cap)) { free(next); return false; }
    if (!gsj_read_u32(json, "wallet_container_id", GAME_STATE_WALLET_CONTAINER_ID_MIN, GAME_STATE_WALLET_CONTAINER_ID_MAX, &next->wallet_container_id, error, error_cap)) { free(next); return false; }
    if (!game_state_validate(next, error, error_cap)) { free(next); return false; }
    *state = *next;
    free(next);
    return true;
}

static void   frag_reset(void)                                             { game_state_init_defaults(&game_state); }

static bool   frag_write_text(game_save_text_writer_t *w)                 { return game_state_write_text(&game_state, w); }
static bool   frag_from_text(const char *t, size_t n, char *e, int c)       { return game_state_from_text(&game_state, t, n, e, c); }
#if !defined(GAME_SAVE_TEXT_ONLY)
static cJSON *frag_to_json(void)                                           { return game_state_to_json(&game_state); }
static bool   frag_write_snapshot(game_save_writer_t *w)                   { return game_state_write_snapshot(&game_state, w); }
static bool   frag_from_json(const cJSON *j, char *e, int c)               { return game_state_from_json(&game_state, j, e, c); }
static cJSON *frag_get_path(const char *s, char *e, int c)                 { return game_state_get_path_json(&game_state, s, e, c); }
static bool   frag_set_path(const char *s, const cJSON *v, char *e, int c) { return game_state_set_path_json(&game_state, s, v, e, c); }
static cJSON *frag_schema(void)                                            { return game_state_schema_json(); }
#endif

extern void game_on_new_game(void);
extern void game_reconcile(void);

const GameSaveFragment game_state_fragment = {
    .id            = GAME_STATE_FRAGMENT_ID,
    .version       = GAME_STATE_VERSION,
    .steps         = NULL,
    .reset         = frag_reset,
    .on_new_game   = game_on_new_game,
#if defined(GAME_SAVE_TEXT_ONLY)
    .to_json       = NULL,
    .from_json     = NULL,
#else
    .to_json       = frag_to_json,
    .from_json     = frag_from_json,
#endif
    .reconcile     = game_reconcile,
#if defined(GAME_SAVE_TEXT_ONLY)
    .get_path_json = NULL,
    .set_path_json = NULL,
    .schema_json   = NULL,
    .write_snapshot = NULL,
#else
    .get_path_json = frag_get_path,
    .set_path_json = frag_set_path,
    .schema_json   = frag_schema,
    .write_snapshot = frag_write_snapshot,
#endif
    .write_text     = frag_write_text,
    .from_text      = frag_from_text,
};
