#include "game_state.h"

#if NT_DEVAPI_ENABLED

/* Generated by features/game-state/scripts/generate_state.py from templates/template/state/game_state.schema.json.
   Transitional single-fragment DevAPI (A5 replaces this with the shell registry
   dispatch). Routes through the fragment descriptor + game_save shell; there is
   no shared global state and no monolith file I/O. */

#include <stdio.h>
#include <string.h>

#include "devapi/nt_devapi.h"
#include "game_save.h"

/* Dev-only, single-threaded: one static buffer for dynamic error messages the
   engine reads after the handler returns (err->message must outlive the call). */
static char s_state_err[256];

static bool state_fail(nt_devapi_error *err, const char *code, const char *message) {
    (void)snprintf(s_state_err, sizeof(s_state_err), "%s", message);
    err->code = code;
    err->message = s_state_err;
    return false;
}

/* err already carries a message snprintf'd into s_state_err by a game_state_* call. */
static bool state_fail_buf(nt_devapi_error *err, const char *code) {
    err->code = code;
    err->message = s_state_err;
    return false;
}

/* game_state_* helpers return freshly-built cJSON; the engine ABI fills a pre-created
   object, so transplant src's members into result_obj. */
static bool state_emit(cJSON *result_obj, cJSON *src, nt_devapi_error *err) {
    if (!src) {
        return state_fail(err, "internal", "failed to build state json");
    }
    cJSON *child = src->child;
    while (child) {
        cJSON *next = child->next;
        cJSON_DetachItemViaPointer(src, child);
        cJSON_AddItemToObject(result_obj, child->string, child);
        child = next;
    }
    cJSON_Delete(src);
    return true;
}

static bool check_doc(const cJSON *params, nt_devapi_error *err) {
    const cJSON *doc = cJSON_GetObjectItemCaseSensitive(params, "doc");
    if (!doc || (cJSON_IsString(doc) && strcmp(doc->valuestring, "game") == 0)) {
        return true;
    }
    return state_fail(err, "bad_params", "unsupported state document");
}

static bool ep_state_schema(const cJSON *params, cJSON *result_obj, nt_devapi_error *err, void *user) {
    (void)user;
    if (!check_doc(params, err)) { return false; }
    return state_emit(result_obj, game_state_schema_json(), err);
}

static bool ep_state_get(const cJSON *params, cJSON *result_obj, nt_devapi_error *err, void *user) {
    (void)user;
    if (!check_doc(params, err)) { return false; }
    const cJSON *path = cJSON_GetObjectItemCaseSensitive(params, "path");
    const char *state_path = cJSON_IsString(path) ? path->valuestring : "";
    cJSON *value = game_state_get_path_json(&game_state, state_path, s_state_err, (int)sizeof(s_state_err));
    if (!value) {
        return state_fail_buf(err, "bad_params");
    }
    /* result_obj is an object, but a path value can be any JSON, so wrap it. */
    cJSON_AddItemToObject(result_obj, "path", cJSON_CreateString(state_path));
    cJSON_AddItemToObject(result_obj, "value", value);
    return true;
}

static bool ep_state_set(const cJSON *params, cJSON *result_obj, nt_devapi_error *err, void *user) {
    (void)user;
    if (!check_doc(params, err)) { return false; }
    const cJSON *path = cJSON_GetObjectItemCaseSensitive(params, "path");
    const cJSON *value = cJSON_GetObjectItemCaseSensitive(params, "value");
    if (!cJSON_IsString(path) || !value) {
        return state_fail(err, "bad_params", "path and value are required");
    }
    if (!game_state_set_path_json(&game_state, path->valuestring, value, s_state_err, (int)sizeof(s_state_err))) {
        return state_fail_buf(err, "bad_params");
    }
    game_save_mark_dirty();
    return state_emit(result_obj, game_state_to_json(&game_state), err);
}

static bool ep_state_patch(const cJSON *params, cJSON *result_obj, nt_devapi_error *err, void *user) {
    (void)user;
    if (!check_doc(params, err)) { return false; }
    const cJSON *values = cJSON_GetObjectItemCaseSensitive(params, "values");
    if (!cJSON_IsObject(values)) {
        return state_fail(err, "bad_params", "values object is required");
    }
    if (!game_state_patch_json(&game_state, values, s_state_err, (int)sizeof(s_state_err))) {
        return state_fail_buf(err, "bad_params");
    }
    game_save_mark_dirty();
    return state_emit(result_obj, game_state_to_json(&game_state), err);
}

static bool ep_state_reset(const cJSON *params, cJSON *result_obj, nt_devapi_error *err, void *user) {
    (void)user;
    if (!check_doc(params, err)) { return false; }
    game_state_init_defaults(&game_state);
    game_save_mark_dirty();
    return state_emit(result_obj, game_state_to_json(&game_state), err);
}

static bool ep_state_save(const cJSON *params, cJSON *result_obj, nt_devapi_error *err, void *user) {
    (void)user;
    if (!check_doc(params, err)) { return false; }
    if (!game_save_flush(s_state_err, (int)sizeof(s_state_err))) {
        return state_fail_buf(err, "internal");
    }
    cJSON *obj = cJSON_CreateObject();
    cJSON_AddBoolToObject(obj, "saved", true);
    return state_emit(result_obj, obj, err);
}

static bool ep_state_load(const cJSON *params, cJSON *result_obj, nt_devapi_error *err, void *user) {
    (void)user;
    if (!check_doc(params, err)) { return false; }
    game_save_load_result_t result;
    game_save_load(&result);
    return state_emit(result_obj, game_state_to_json(&game_state), err);
}

void game_state_register_devapi(void) {
    static const nt_devapi_command_desc descs[] = {
        {"game.state.schema", "game", "Return the game state JSON schema.", "doc?", "schema object", "immediate", "none"},
        {"game.state.get", "game", "Get a state value by path.", "doc?, path", "path, value", "immediate", "none"},
        {"game.state.set", "game", "Set a state value by path.", "doc?, path, value", "state object", "immediate", "mutates state"},
        {"game.state.patch", "game", "Patch multiple state values.", "doc?, values", "state object", "immediate", "mutates state"},
        {"game.state.save", "game", "Flush state to storage.", "doc?", "saved", "immediate", "writes file"},
        {"game.state.load", "game", "Reload state from storage.", "doc?", "state object", "immediate", "mutates state"},
        {"game.state.reset", "game", "Reset state to defaults.", "doc?", "state object", "immediate", "mutates state"},
    };
    const nt_devapi_handler_fn fns[] = {
        ep_state_schema, ep_state_get, ep_state_set, ep_state_patch,
        ep_state_save, ep_state_load, ep_state_reset,
    };
    for (size_t i = 0; i < sizeof(fns) / sizeof(fns[0]); ++i) {
        (void)nt_devapi_register(&descs[i], fns[i], NULL);
    }
}

#endif
