#ifndef GAME_STATE_GENERATED_H
#define GAME_STATE_GENERATED_H

/* Generated by features/game-state/scripts/generate_state.py from templates/template/state/game_state.schema.json. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "cJSON.h"
#include "game_save.h"

#define GAME_STATE_SCHEMA_ID "game_seed.state"
#define GAME_STATE_FRAGMENT_ID "game"
#define GAME_STATE_VERSION 1
#define GAME_STATE_STRING_MAX 64

#define GAME_STATE_SHAPE_INDEX_DEFAULT GAME_STATE_SHAPE_CUBE
#define GAME_STATE_RENDER_MODE_INDEX_DEFAULT GAME_STATE_RENDER_MODE_SOLID_WIRE
#define GAME_STATE_CAMERA_DISTANCE_DEFAULT 6.0F
#define GAME_STATE_CAMERA_DISTANCE_MIN 2.5F
#define GAME_STATE_CAMERA_DISTANCE_MAX 10.0F
#define GAME_STATE_TEST_UI_CLICKS_DEFAULT 0
#define GAME_STATE_TEST_UI_CLICKS_MIN 0
#define GAME_STATE_TEST_UI_CLICKS_MAX 1000000
#define GAME_STATE_TEST_LABEL_TEXT_DEFAULT "Template ready"
#define GAME_STATE_TEST_BUTTON_TEXT_DEFAULT "Cycle"
#define GAME_STATE_TUTORIAL_DONE_DEFAULT 0

typedef enum GameStateShape {
    GAME_STATE_SHAPE_CUBE = 0,
    GAME_STATE_SHAPE_SPHERE,
    GAME_STATE_SHAPE_CYLINDER,
    GAME_STATE_SHAPE_CAPSULE,
    GAME_STATE_SHAPE_COUNT,
} GameStateShape;

typedef enum GameStateRenderMode {
    GAME_STATE_RENDER_MODE_SOLID_WIRE = 0,
    GAME_STATE_RENDER_MODE_SOLID,
    GAME_STATE_RENDER_MODE_WIRE,
    GAME_STATE_RENDER_MODE_COUNT,
} GameStateRenderMode;



typedef struct GameState {
    int shape_index;
    int render_mode_index;
    float camera_distance;
    int test_ui_clicks;
    char test_label_text[GAME_STATE_STRING_MAX];
    char test_button_text[GAME_STATE_STRING_MAX];
    bool tutorial_done;
} GameState;

/* Instance owned by this fragment TU (the shared global-state monolith is gone).
   Feature LOGIC works with it directly or through its own API. */
extern GameState game_state;

const char *game_state_shape_name(int value);
const char *game_state_render_mode_name(int value);

void   game_state_init_defaults(GameState *state);
bool   game_state_validate(const GameState *state, char *error, int error_cap);
cJSON *game_state_schema_json(void);
cJSON *game_state_to_json(const GameState *state);
cJSON *game_state_get_path_json(const GameState *state, const char *path, char *error, int error_cap);
bool   game_state_set_path_json(GameState *state, const char *path, const cJSON *value, char *error, int error_cap);
bool   game_state_patch_json(GameState *state, const cJSON *values, char *error, int error_cap);
bool   game_state_from_json(GameState *state, const cJSON *json, char *error, int error_cap);

/* Generated descriptor — replaces the hand-written fragment adapter. */
extern const GameSaveFragment game_state_fragment;

#endif
