#ifndef GAME_STATE_SCHEMA_GEN_H
#define GAME_STATE_SCHEMA_GEN_H

/* Generated by features/game-state/scripts/generate_state.py from state/game_state.schema.json. */
#define GAME_STATE_SCHEMA_JSON_CHUNKS \
    { \
    "{\"schema\":\"game_seed.state\",\"document\":\"game\",\"fragment\":\"game\",\"version\":1,\"schema_version\":2,\"string_max\":64,\"enums\":{\"Shape\":[\"cube\",\"sphere\",\"cylinder\",\"capsule\"],\"RenderMode\":[\"solid_wire\",\"solid\",\"wire\"]},\"types\":{},\"fields\":[{\"path\":\"shape_index\",\"type\":\"enum\",\"enum\":\"Shape\",\"default\":\"cube\"},{\"path\":\"render_mode_index\",\"type\":\"enum\",\"enum\":\"RenderMode\",\"default\":\"solid_wire\"},{\"path\":\"camera_distance\",\"type\":\"float\",\"default\":6,\"min\":2.5,\"max\":10},{\"path\":\"test_ui_clicks\",\"type\":\"int\",\"default\":0,\"min\":0,\"max\":1000000},{\"path\":\"test_label_text\",\"type\":\"string\",\"default\":\"Template ready\",\"max_length\":63},{\"path\":\"test_button_text\",\"type\":\"string\",\"default\":\"Cycle\",\"max_length\":63},{\"path\":\"tutorial.done\",\"type\":\"bool\",\"default\":false}]}", \
    "" \
    }

#endif
