#include "game_state.h"
#include "game_state_schema.gen.h"
#include "game_state_json.h"

/* Generated by features/game-state/scripts/generate_state.py from templates/template/state/game_state.schema.json. */

#include <stdlib.h>
#include <string.h>

static const char *const k_shape_names[GAME_STATE_SHAPE_COUNT] = {
    "cube",
    "sphere",
    "cylinder",
    "capsule",
};

static const char *const k_render_mode_names[GAME_STATE_RENDER_MODE_COUNT] = {
    "solid_wire",
    "solid",
    "wire",
};

static const char *const k_location_names[GAME_STATE_LOCATION_COUNT] = {
    "old_gate",
    "north_road",
    "old_mine",
};

static const char *const k_quest_stage_names[GAME_STATE_QUEST_STAGE_COUNT] = {
    "not_started",
    "accepted",
    "wolf_defeated",
    "completed",
};

static const char *const k_battle_state_names[GAME_STATE_BATTLE_STATE_COUNT] = {
    "none",
    "ready",
    "running",
    "victory",
    "low_health",
    "defeat",
};

const char *game_state_shape_name(int value) {
    return (value >= 0 && value < GAME_STATE_SHAPE_COUNT) ? k_shape_names[value] : "unknown";
}

const char *game_state_render_mode_name(int value) {
    return (value >= 0 && value < GAME_STATE_RENDER_MODE_COUNT) ? k_render_mode_names[value] : "unknown";
}

const char *game_state_location_name(int value) {
    return (value >= 0 && value < GAME_STATE_LOCATION_COUNT) ? k_location_names[value] : "unknown";
}

const char *game_state_quest_stage_name(int value) {
    return (value >= 0 && value < GAME_STATE_QUEST_STAGE_COUNT) ? k_quest_stage_names[value] : "unknown";
}

const char *game_state_battle_state_name(int value) {
    return (value >= 0 && value < GAME_STATE_BATTLE_STATE_COUNT) ? k_battle_state_names[value] : "unknown";
}

GameState game_state;   /* fragment instance (ownership lives here) */

static void item_instance_init_defaults(GameItemInstance *obj, const char *key) {
    memset(obj, 0, sizeof(*obj));
    obj->used = true;
    (void)gsj_copy_text(obj->key, sizeof(obj->key), key);
    obj->count = GAME_STATE_ITEM_INSTANCE_COUNT_DEFAULT;
    obj->level = GAME_STATE_ITEM_INSTANCE_LEVEL_DEFAULT;
    obj->durability = GAME_STATE_ITEM_INSTANCE_DURABILITY_DEFAULT;
}

static bool item_instance_validate(const GameItemInstance *obj, char *error, int error_cap) {
    if (!obj->used) { return true; }
    if (obj->key[0] == '\0') { gsj_set_error(error, error_cap, "object key is empty"); return false; }
    if (obj->def_id[0] == '\0') {
        gsj_set_error(error, error_cap, "def_id out of range");
        return false;
    }
    if (obj->count < GAME_STATE_ITEM_INSTANCE_COUNT_MIN || obj->count > GAME_STATE_ITEM_INSTANCE_COUNT_MAX) {
        gsj_set_error(error, error_cap, "count out of range");
        return false;
    }
    if (obj->level < GAME_STATE_ITEM_INSTANCE_LEVEL_MIN || obj->level > GAME_STATE_ITEM_INSTANCE_LEVEL_MAX) {
        gsj_set_error(error, error_cap, "level out of range");
        return false;
    }
    if (obj->durability < GAME_STATE_ITEM_INSTANCE_DURABILITY_MIN || obj->durability > GAME_STATE_ITEM_INSTANCE_DURABILITY_MAX) {
        gsj_set_error(error, error_cap, "durability out of range");
        return false;
    }
    return true;
}

static cJSON *item_instance_to_json(const GameItemInstance *obj) {
    cJSON *json = cJSON_CreateObject();
    cJSON_AddStringToObject(json, "def_id", obj->def_id);
    gsj_add_i64(json, "count", obj->count);
    cJSON_AddNumberToObject(json, "level", obj->level);
    cJSON_AddNumberToObject(json, "durability", (double)obj->durability);
    return json;
}

static cJSON *item_instance_get_field_json(const GameItemInstance *obj, const char *field, char *error, int error_cap) {
    if (!field || field[0] == '\0') { return item_instance_to_json(obj); }
    if (strcmp(field, "def_id") == 0) {
        return cJSON_CreateString(obj->def_id);
    }
    if (strcmp(field, "count") == 0) {
        return cJSON_CreateString(gsj_i64_to_string(obj->count, (char[21]){0}, 21));
    }
    if (strcmp(field, "level") == 0) {
        return cJSON_CreateNumber(obj->level);
    }
    if (strcmp(field, "durability") == 0) {
        return cJSON_CreateNumber((double)obj->durability);
    }
    gsj_set_error(error, error_cap, "unknown object field");
    return NULL;
}

static bool item_instance_set_field_json(GameItemInstance *obj, const char *field, const cJSON *value, char *error, int error_cap) {
    if (strcmp(field, "def_id") == 0) {
        if (!cJSON_IsString(value) || !gsj_copy_text(obj->def_id, sizeof(obj->def_id), value->valuestring)) { gsj_set_error(error, error_cap, "expected short string"); return false; }
        return true;
    }
    if (strcmp(field, "count") == 0) {
        if (!gsj_parse_i64_value(value, GAME_STATE_ITEM_INSTANCE_COUNT_MIN, GAME_STATE_ITEM_INSTANCE_COUNT_MAX, &obj->count, error, error_cap)) { return false; }
        return true;
    }
    if (strcmp(field, "level") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_ITEM_INSTANCE_LEVEL_MIN, GAME_STATE_ITEM_INSTANCE_LEVEL_MAX, &parsed, error, error_cap)) { return false; }
        obj->level = parsed;
        return true;
    }
    if (strcmp(field, "durability") == 0) {
        if (!cJSON_IsNumber(value)) { gsj_set_error(error, error_cap, "expected number"); return false; }
        float parsed = (float)value->valuedouble;
        if (parsed < GAME_STATE_ITEM_INSTANCE_DURABILITY_MIN || parsed > GAME_STATE_ITEM_INSTANCE_DURABILITY_MAX) { gsj_set_error(error, error_cap, "number out of range"); return false; }
        obj->durability = parsed;
        return true;
    }
    gsj_set_error(error, error_cap, "unknown object field");
    return false;
}

static bool item_instance_from_json(GameItemInstance *obj, const cJSON *json, char *error, int error_cap) {
    if (!cJSON_IsObject(json)) { gsj_set_error(error, error_cap, "object must be json object"); return false; }
    if (!gsj_read_string(json, "def_id", obj->def_id, sizeof(obj->def_id), error, error_cap)) { return false; }
    if (!gsj_read_i64(json, "count", GAME_STATE_ITEM_INSTANCE_COUNT_MIN, GAME_STATE_ITEM_INSTANCE_COUNT_MAX, &obj->count, error, error_cap)) { return false; }
    if (!gsj_read_int_range(json, "level", GAME_STATE_ITEM_INSTANCE_LEVEL_MIN, GAME_STATE_ITEM_INSTANCE_LEVEL_MAX, &obj->level, error, error_cap)) { return false; }
    if (!gsj_read_float_range(json, "durability", GAME_STATE_ITEM_INSTANCE_DURABILITY_MIN, GAME_STATE_ITEM_INSTANCE_DURABILITY_MAX, &obj->durability, error, error_cap)) { return false; }
    return item_instance_validate(obj, error, error_cap);
}


static GameItemInstance *find_items(GameState *state, const char *key) {
    for (int i = 0; i < GAME_STATE_MAX_ITEMS; i++) {
        if (state->items[i].used && strcmp(state->items[i].key, key) == 0) {
            return &state->items[i];
        }
    }
    return NULL;
}

static const GameItemInstance *find_items_const(const GameState *state, const char *key) {
    for (int i = 0; i < GAME_STATE_MAX_ITEMS; i++) {
        if (state->items[i].used && strcmp(state->items[i].key, key) == 0) {
            return &state->items[i];
        }
    }
    return NULL;
}

static GameItemInstance *alloc_items(GameState *state, const char *key) {
    GameItemInstance *existing = find_items(state, key);
    if (existing) { return existing; }
    for (int i = 0; i < GAME_STATE_MAX_ITEMS; i++) {
        if (!state->items[i].used) {
            item_instance_init_defaults(&state->items[i], key);
            return state->items[i].used ? &state->items[i] : NULL;
        }
    }
    return NULL;
}

static cJSON *items_to_json(const GameState *state) {
    cJSON *json = cJSON_CreateObject();
    for (int i = 0; i < GAME_STATE_MAX_ITEMS; i++) {
        if (state->items[i].used) {
            cJSON_AddItemToObject(json, state->items[i].key, item_instance_to_json(&state->items[i]));
        }
    }
    return json;
}

static bool set_items_from_json(GameState *state, const cJSON *json, char *error, int error_cap) {
    if (!cJSON_IsObject(json)) { gsj_set_error(error, error_cap, "map must be object"); return false; }
    for (int i = 0; i < GAME_STATE_MAX_ITEMS; i++) { memset(&state->items[i], 0, sizeof(state->items[i])); }
    const cJSON *child = NULL;
    cJSON_ArrayForEach(child, json) {
        if (!child->string) { continue; }
        GameItemInstance *obj = alloc_items(state, child->string);
        if (!obj) { gsj_set_error(error, error_cap, "too many map entries or long key"); return false; }
        if (!item_instance_from_json(obj, child, error, error_cap)) { return false; }
    }
    return true;
}



static cJSON *inventory_item_ids_to_json(const GameState *state) {
    cJSON *json = cJSON_CreateArray();
    for (int i = 0; i < state->inventory_item_ids_count; i++) {
        cJSON_AddItemToArray(json, cJSON_CreateString(state->inventory_item_ids[i]));
    }
    return json;
}

static bool set_inventory_item_ids_from_json(GameState *state, const cJSON *json, char *error, int error_cap) {
    if (!cJSON_IsArray(json)) { gsj_set_error(error, error_cap, "list must be array"); return false; }
    int count = cJSON_GetArraySize((cJSON *)json);
    if (count > GAME_STATE_MAX_INVENTORY_ITEM_IDS) { gsj_set_error(error, error_cap, "too many list entries"); return false; }
    state->inventory_item_ids_count = 0;
    for (int i = 0; i < count; i++) {
        const cJSON *entry = cJSON_GetArrayItem((cJSON *)json, i);
        if (!cJSON_IsString(entry) || !gsj_copy_text(state->inventory_item_ids[i], sizeof(state->inventory_item_ids[i]), entry->valuestring)) {
            gsj_set_error(error, error_cap, "list entry must be short string");
            return false;
        }
        state->inventory_item_ids_count++;
    }
    return true;
}


void game_state_init_defaults(GameState *state) {
    memset(state, 0, sizeof(*state));
    state->shape_index = GAME_STATE_SHAPE_INDEX_DEFAULT;
    state->render_mode_index = GAME_STATE_RENDER_MODE_INDEX_DEFAULT;
    state->camera_distance = GAME_STATE_CAMERA_DISTANCE_DEFAULT;
    state->test_ui_clicks = GAME_STATE_TEST_UI_CLICKS_DEFAULT;
    (void)gsj_copy_text(state->test_label_text, sizeof(state->test_label_text), GAME_STATE_TEST_LABEL_TEXT_DEFAULT);
    (void)gsj_copy_text(state->test_button_text, sizeof(state->test_button_text), GAME_STATE_TEST_BUTTON_TEXT_DEFAULT);
    state->tutorial_done = GAME_STATE_TUTORIAL_DONE_DEFAULT;
    state->wallet_soft = GAME_STATE_WALLET_SOFT_DEFAULT;
    state->wallet_hard = GAME_STATE_WALLET_HARD_DEFAULT;
    state->has_equipment_hand_item_id = false;
    state->hero_level = GAME_STATE_HERO_LEVEL_DEFAULT;
    state->hero_xp = GAME_STATE_HERO_XP_DEFAULT;
    state->hero_hp = GAME_STATE_HERO_HP_DEFAULT;
    state->hero_hp_max = GAME_STATE_HERO_HP_MAX_DEFAULT;
    state->hero_attack = GAME_STATE_HERO_ATTACK_DEFAULT;
    state->hero_defense = GAME_STATE_HERO_DEFENSE_DEFAULT;
    state->hero_gold = GAME_STATE_HERO_GOLD_DEFAULT;
    state->location_index = GAME_STATE_LOCATION_INDEX_DEFAULT;
    state->quest_stage_index = GAME_STATE_QUEST_STAGE_INDEX_DEFAULT;
    state->battle_state_index = GAME_STATE_BATTLE_STATE_INDEX_DEFAULT;
    state->battle_round = GAME_STATE_BATTLE_ROUND_DEFAULT;
    state->battle_enemy_hp = GAME_STATE_BATTLE_ENEMY_HP_DEFAULT;
    state->battle_enemy_hp_max = GAME_STATE_BATTLE_ENEMY_HP_MAX_DEFAULT;
    state->battle_enemy_attack = GAME_STATE_BATTLE_ENEMY_ATTACK_DEFAULT;
    state->battle_enemy_defense = GAME_STATE_BATTLE_ENEMY_DEFENSE_DEFAULT;
    state->battle_last_damage = GAME_STATE_BATTLE_LAST_DAMAGE_DEFAULT;
    state->battle_last_enemy_damage = GAME_STATE_BATTLE_LAST_ENEMY_DAMAGE_DEFAULT;
    state->battle_wins = GAME_STATE_BATTLE_WINS_DEFAULT;
    state->quest_wolf_kills = GAME_STATE_QUEST_WOLF_KILLS_DEFAULT;
    state->reward_pending = GAME_STATE_REWARD_PENDING_DEFAULT;
    state->reward_item_ready = GAME_STATE_REWARD_ITEM_READY_DEFAULT;
    state->gear_ring_equipped = GAME_STATE_GEAR_RING_EQUIPPED_DEFAULT;
    state->old_mine_scouted = GAME_STATE_OLD_MINE_SCOUTED_DEFAULT;
    state->old_mine_depth = GAME_STATE_OLD_MINE_DEPTH_DEFAULT;
    state->old_mine_ember_shards = GAME_STATE_OLD_MINE_EMBER_SHARDS_DEFAULT;
    state->old_mine_depth_resolved = GAME_STATE_OLD_MINE_DEPTH_RESOLVED_DEFAULT;
    state->old_mine_bat_defeated = GAME_STATE_OLD_MINE_BAT_DEFEATED_DEFAULT;
    state->old_mine_bat_damage = GAME_STATE_OLD_MINE_BAT_DAMAGE_DEFAULT;
    state->old_mine_depth_gold = GAME_STATE_OLD_MINE_DEPTH_GOLD_DEFAULT;
    state->old_mine_delve_count = GAME_STATE_OLD_MINE_DELVE_COUNT_DEFAULT;
    state->old_mine_cache_claimed = GAME_STATE_OLD_MINE_CACHE_CLAIMED_DEFAULT;
    state->old_mine_last_delve_shards = GAME_STATE_OLD_MINE_LAST_DELVE_SHARDS_DEFAULT;
    state->old_mine_last_delve_gold = GAME_STATE_OLD_MINE_LAST_DELVE_GOLD_DEFAULT;
    state->old_mine_last_delve_xp = GAME_STATE_OLD_MINE_LAST_DELVE_XP_DEFAULT;
    state->gear_mine_lantern = GAME_STATE_GEAR_MINE_LANTERN_DEFAULT;
    state->old_mine_depth2_unlocked = GAME_STATE_OLD_MINE_DEPTH2_UNLOCKED_DEFAULT;
}

bool game_state_validate(const GameState *state, char *error, int error_cap) {
    if (!state) { gsj_set_error(error, error_cap, "state is null"); return false; }
    if (state->shape_index < 0 || state->shape_index >= GAME_STATE_SHAPE_COUNT) {
        gsj_set_error(error, error_cap, "shape_index out of range");
        return false;
    }
    if (state->render_mode_index < 0 || state->render_mode_index >= GAME_STATE_RENDER_MODE_COUNT) {
        gsj_set_error(error, error_cap, "render_mode_index out of range");
        return false;
    }
    if (state->camera_distance < GAME_STATE_CAMERA_DISTANCE_MIN || state->camera_distance > GAME_STATE_CAMERA_DISTANCE_MAX) {
        gsj_set_error(error, error_cap, "camera_distance out of range");
        return false;
    }
    if (state->test_ui_clicks < GAME_STATE_TEST_UI_CLICKS_MIN || state->test_ui_clicks > GAME_STATE_TEST_UI_CLICKS_MAX) {
        gsj_set_error(error, error_cap, "test_ui_clicks out of range");
        return false;
    }
    if (state->test_label_text[0] == '\0') {
        gsj_set_error(error, error_cap, "test_label_text out of range");
        return false;
    }
    if (state->test_button_text[0] == '\0') {
        gsj_set_error(error, error_cap, "test_button_text out of range");
        return false;
    }
    if (state->wallet_soft < GAME_STATE_WALLET_SOFT_MIN || state->wallet_soft > GAME_STATE_WALLET_SOFT_MAX) {
        gsj_set_error(error, error_cap, "wallet.soft out of range");
        return false;
    }
    if (state->wallet_hard < GAME_STATE_WALLET_HARD_MIN || state->wallet_hard > GAME_STATE_WALLET_HARD_MAX) {
        gsj_set_error(error, error_cap, "wallet.hard out of range");
        return false;
    }
    if (state->hero_level < GAME_STATE_HERO_LEVEL_MIN || state->hero_level > GAME_STATE_HERO_LEVEL_MAX) {
        gsj_set_error(error, error_cap, "hero.level out of range");
        return false;
    }
    if (state->hero_xp < GAME_STATE_HERO_XP_MIN || state->hero_xp > GAME_STATE_HERO_XP_MAX) {
        gsj_set_error(error, error_cap, "hero.xp out of range");
        return false;
    }
    if (state->hero_hp < GAME_STATE_HERO_HP_MIN || state->hero_hp > GAME_STATE_HERO_HP_MAX) {
        gsj_set_error(error, error_cap, "hero.hp out of range");
        return false;
    }
    if (state->hero_hp_max < GAME_STATE_HERO_HP_MAX_MIN || state->hero_hp_max > GAME_STATE_HERO_HP_MAX_MAX) {
        gsj_set_error(error, error_cap, "hero.hp_max out of range");
        return false;
    }
    if (state->hero_attack < GAME_STATE_HERO_ATTACK_MIN || state->hero_attack > GAME_STATE_HERO_ATTACK_MAX) {
        gsj_set_error(error, error_cap, "hero.attack out of range");
        return false;
    }
    if (state->hero_defense < GAME_STATE_HERO_DEFENSE_MIN || state->hero_defense > GAME_STATE_HERO_DEFENSE_MAX) {
        gsj_set_error(error, error_cap, "hero.defense out of range");
        return false;
    }
    if (state->hero_gold < GAME_STATE_HERO_GOLD_MIN || state->hero_gold > GAME_STATE_HERO_GOLD_MAX) {
        gsj_set_error(error, error_cap, "hero.gold out of range");
        return false;
    }
    if (state->location_index < 0 || state->location_index >= GAME_STATE_LOCATION_COUNT) {
        gsj_set_error(error, error_cap, "location_index out of range");
        return false;
    }
    if (state->quest_stage_index < 0 || state->quest_stage_index >= GAME_STATE_QUEST_STAGE_COUNT) {
        gsj_set_error(error, error_cap, "quest_stage_index out of range");
        return false;
    }
    if (state->battle_state_index < 0 || state->battle_state_index >= GAME_STATE_BATTLE_STATE_COUNT) {
        gsj_set_error(error, error_cap, "battle_state_index out of range");
        return false;
    }
    if (state->battle_round < GAME_STATE_BATTLE_ROUND_MIN || state->battle_round > GAME_STATE_BATTLE_ROUND_MAX) {
        gsj_set_error(error, error_cap, "battle.round out of range");
        return false;
    }
    if (state->battle_enemy_hp < GAME_STATE_BATTLE_ENEMY_HP_MIN || state->battle_enemy_hp > GAME_STATE_BATTLE_ENEMY_HP_MAX) {
        gsj_set_error(error, error_cap, "battle.enemy_hp out of range");
        return false;
    }
    if (state->battle_enemy_hp_max < GAME_STATE_BATTLE_ENEMY_HP_MAX_MIN || state->battle_enemy_hp_max > GAME_STATE_BATTLE_ENEMY_HP_MAX_MAX) {
        gsj_set_error(error, error_cap, "battle.enemy_hp_max out of range");
        return false;
    }
    if (state->battle_enemy_attack < GAME_STATE_BATTLE_ENEMY_ATTACK_MIN || state->battle_enemy_attack > GAME_STATE_BATTLE_ENEMY_ATTACK_MAX) {
        gsj_set_error(error, error_cap, "battle.enemy_attack out of range");
        return false;
    }
    if (state->battle_enemy_defense < GAME_STATE_BATTLE_ENEMY_DEFENSE_MIN || state->battle_enemy_defense > GAME_STATE_BATTLE_ENEMY_DEFENSE_MAX) {
        gsj_set_error(error, error_cap, "battle.enemy_defense out of range");
        return false;
    }
    if (state->battle_last_damage < GAME_STATE_BATTLE_LAST_DAMAGE_MIN || state->battle_last_damage > GAME_STATE_BATTLE_LAST_DAMAGE_MAX) {
        gsj_set_error(error, error_cap, "battle.last_damage out of range");
        return false;
    }
    if (state->battle_last_enemy_damage < GAME_STATE_BATTLE_LAST_ENEMY_DAMAGE_MIN || state->battle_last_enemy_damage > GAME_STATE_BATTLE_LAST_ENEMY_DAMAGE_MAX) {
        gsj_set_error(error, error_cap, "battle.last_enemy_damage out of range");
        return false;
    }
    if (state->battle_wins < GAME_STATE_BATTLE_WINS_MIN || state->battle_wins > GAME_STATE_BATTLE_WINS_MAX) {
        gsj_set_error(error, error_cap, "battle.wins out of range");
        return false;
    }
    if (state->quest_wolf_kills < GAME_STATE_QUEST_WOLF_KILLS_MIN || state->quest_wolf_kills > GAME_STATE_QUEST_WOLF_KILLS_MAX) {
        gsj_set_error(error, error_cap, "quest.wolf_kills out of range");
        return false;
    }
    if (state->old_mine_depth < GAME_STATE_OLD_MINE_DEPTH_MIN || state->old_mine_depth > GAME_STATE_OLD_MINE_DEPTH_MAX) {
        gsj_set_error(error, error_cap, "old_mine.depth out of range");
        return false;
    }
    if (state->old_mine_ember_shards < GAME_STATE_OLD_MINE_EMBER_SHARDS_MIN || state->old_mine_ember_shards > GAME_STATE_OLD_MINE_EMBER_SHARDS_MAX) {
        gsj_set_error(error, error_cap, "old_mine.ember_shards out of range");
        return false;
    }
    if (state->old_mine_bat_damage < GAME_STATE_OLD_MINE_BAT_DAMAGE_MIN || state->old_mine_bat_damage > GAME_STATE_OLD_MINE_BAT_DAMAGE_MAX) {
        gsj_set_error(error, error_cap, "old_mine.bat_damage out of range");
        return false;
    }
    if (state->old_mine_depth_gold < GAME_STATE_OLD_MINE_DEPTH_GOLD_MIN || state->old_mine_depth_gold > GAME_STATE_OLD_MINE_DEPTH_GOLD_MAX) {
        gsj_set_error(error, error_cap, "old_mine.depth_gold out of range");
        return false;
    }
    if (state->old_mine_delve_count < GAME_STATE_OLD_MINE_DELVE_COUNT_MIN || state->old_mine_delve_count > GAME_STATE_OLD_MINE_DELVE_COUNT_MAX) {
        gsj_set_error(error, error_cap, "old_mine.delve_count out of range");
        return false;
    }
    if (state->old_mine_last_delve_shards < GAME_STATE_OLD_MINE_LAST_DELVE_SHARDS_MIN || state->old_mine_last_delve_shards > GAME_STATE_OLD_MINE_LAST_DELVE_SHARDS_MAX) {
        gsj_set_error(error, error_cap, "old_mine.last_delve_shards out of range");
        return false;
    }
    if (state->old_mine_last_delve_gold < GAME_STATE_OLD_MINE_LAST_DELVE_GOLD_MIN || state->old_mine_last_delve_gold > GAME_STATE_OLD_MINE_LAST_DELVE_GOLD_MAX) {
        gsj_set_error(error, error_cap, "old_mine.last_delve_gold out of range");
        return false;
    }
    if (state->old_mine_last_delve_xp < GAME_STATE_OLD_MINE_LAST_DELVE_XP_MIN || state->old_mine_last_delve_xp > GAME_STATE_OLD_MINE_LAST_DELVE_XP_MAX) {
        gsj_set_error(error, error_cap, "old_mine.last_delve_xp out of range");
        return false;
    }
    if (state->inventory_item_ids_count < 0 || state->inventory_item_ids_count > GAME_STATE_MAX_INVENTORY_ITEM_IDS) {
        gsj_set_error(error, error_cap, "inventory.item_ids count out of range");
        return false;
    }
    for (int i = 0; i < state->inventory_item_ids_count; i++) {
        if (state->inventory_item_ids[i][0] == '\0') {
            gsj_set_error(error, error_cap, "inventory.item_ids contains empty id");
            return false;
        }
    }
    for (int i = 0; i < GAME_STATE_MAX_ITEMS; i++) {
        if (state->items[i].used && !item_instance_validate(&state->items[i], error, error_cap)) {
            return false;
        }
    }
    return true;
}

cJSON *game_state_schema_json(void) {
    const char *chunks[] = GAME_STATE_SCHEMA_JSON_CHUNKS;
    size_t len = 0;
    for (size_t i = 0; chunks[i][0] != '\0'; i++) { len += strlen(chunks[i]); }
    char *json = (char *)malloc(len + 1U);
    if (!json) { return cJSON_CreateObject(); }
    char *cursor = json;
    for (size_t i = 0; chunks[i][0] != '\0'; i++) {
        size_t chunk_len = strlen(chunks[i]);
        memcpy(cursor, chunks[i], chunk_len);
        cursor += chunk_len;
    }
    json[len] = '\0';
    cJSON *root = cJSON_Parse(json);
    free(json);
    return root ? root : cJSON_CreateObject();
}

cJSON *game_state_to_json(const GameState *state) {
    cJSON *root = cJSON_CreateObject();
    cJSON_AddNumberToObject(root, "shape_index", state->shape_index);
    cJSON_AddStringToObject(root, "shape", game_state_shape_name(state->shape_index));
    cJSON_AddNumberToObject(root, "render_mode_index", state->render_mode_index);
    cJSON_AddStringToObject(root, "render_mode", game_state_render_mode_name(state->render_mode_index));
    cJSON_AddNumberToObject(root, "camera_distance", (double)state->camera_distance);
    cJSON_AddNumberToObject(root, "test_ui_clicks", state->test_ui_clicks);
    cJSON_AddStringToObject(root, "test_label_text", state->test_label_text);
    cJSON_AddStringToObject(root, "test_button_text", state->test_button_text);
    cJSON *tutorial = cJSON_AddObjectToObject(root, "tutorial");
    cJSON_AddBoolToObject(tutorial, "done", state->tutorial_done);
    cJSON *wallet = cJSON_AddObjectToObject(root, "wallet");
    gsj_add_i64(wallet, "soft", state->wallet_soft);
    gsj_add_i64(wallet, "hard", state->wallet_hard);
    cJSON_AddItemToObject(root, "items", items_to_json(state));
    cJSON *inventory = cJSON_AddObjectToObject(root, "inventory");
    cJSON_AddItemToObject(inventory, "item_ids", inventory_item_ids_to_json(state));
    cJSON *equipment = cJSON_AddObjectToObject(root, "equipment");
    if (state->has_equipment_hand_item_id) {
        cJSON_AddStringToObject(equipment, "hand_item_id", state->equipment_hand_item_id);
    } else {
        cJSON_AddNullToObject(equipment, "hand_item_id");
    }
    cJSON *hero = cJSON_AddObjectToObject(root, "hero");
    cJSON_AddNumberToObject(hero, "level", state->hero_level);
    cJSON_AddNumberToObject(hero, "xp", state->hero_xp);
    cJSON_AddNumberToObject(hero, "hp", state->hero_hp);
    cJSON_AddNumberToObject(hero, "hp_max", state->hero_hp_max);
    cJSON_AddNumberToObject(hero, "attack", state->hero_attack);
    cJSON_AddNumberToObject(hero, "defense", state->hero_defense);
    cJSON_AddNumberToObject(hero, "gold", state->hero_gold);
    cJSON_AddNumberToObject(root, "location_index", state->location_index);
    cJSON_AddStringToObject(root, "location", game_state_location_name(state->location_index));
    cJSON_AddNumberToObject(root, "quest_stage_index", state->quest_stage_index);
    cJSON_AddStringToObject(root, "quest_stage", game_state_quest_stage_name(state->quest_stage_index));
    cJSON_AddNumberToObject(root, "battle_state_index", state->battle_state_index);
    cJSON_AddStringToObject(root, "battle_state", game_state_battle_state_name(state->battle_state_index));
    cJSON *battle = cJSON_AddObjectToObject(root, "battle");
    cJSON_AddNumberToObject(battle, "round", state->battle_round);
    cJSON_AddNumberToObject(battle, "enemy_hp", state->battle_enemy_hp);
    cJSON_AddNumberToObject(battle, "enemy_hp_max", state->battle_enemy_hp_max);
    cJSON_AddNumberToObject(battle, "enemy_attack", state->battle_enemy_attack);
    cJSON_AddNumberToObject(battle, "enemy_defense", state->battle_enemy_defense);
    cJSON_AddNumberToObject(battle, "last_damage", state->battle_last_damage);
    cJSON_AddNumberToObject(battle, "last_enemy_damage", state->battle_last_enemy_damage);
    cJSON_AddNumberToObject(battle, "wins", state->battle_wins);
    cJSON *quest = cJSON_AddObjectToObject(root, "quest");
    cJSON_AddNumberToObject(quest, "wolf_kills", state->quest_wolf_kills);
    cJSON *reward = cJSON_AddObjectToObject(root, "reward");
    cJSON_AddBoolToObject(reward, "pending", state->reward_pending);
    cJSON_AddBoolToObject(reward, "item_ready", state->reward_item_ready);
    cJSON *gear = cJSON_AddObjectToObject(root, "gear");
    cJSON_AddBoolToObject(gear, "ring_equipped", state->gear_ring_equipped);
    cJSON *old_mine = cJSON_AddObjectToObject(root, "old_mine");
    cJSON_AddBoolToObject(old_mine, "scouted", state->old_mine_scouted);
    cJSON_AddNumberToObject(old_mine, "depth", state->old_mine_depth);
    cJSON_AddNumberToObject(old_mine, "ember_shards", state->old_mine_ember_shards);
    cJSON_AddBoolToObject(old_mine, "depth_resolved", state->old_mine_depth_resolved);
    cJSON_AddBoolToObject(old_mine, "bat_defeated", state->old_mine_bat_defeated);
    cJSON_AddNumberToObject(old_mine, "bat_damage", state->old_mine_bat_damage);
    cJSON_AddNumberToObject(old_mine, "depth_gold", state->old_mine_depth_gold);
    cJSON_AddNumberToObject(old_mine, "delve_count", state->old_mine_delve_count);
    cJSON_AddBoolToObject(old_mine, "cache_claimed", state->old_mine_cache_claimed);
    cJSON_AddNumberToObject(old_mine, "last_delve_shards", state->old_mine_last_delve_shards);
    cJSON_AddNumberToObject(old_mine, "last_delve_gold", state->old_mine_last_delve_gold);
    cJSON_AddNumberToObject(old_mine, "last_delve_xp", state->old_mine_last_delve_xp);
    cJSON_AddBoolToObject(gear, "mine_lantern", state->gear_mine_lantern);
    cJSON_AddBoolToObject(old_mine, "depth2_unlocked", state->old_mine_depth2_unlocked);
    return root;
}

cJSON *game_state_get_path_json(const GameState *state, const char *path, char *error, int error_cap) {
    if (!path || path[0] == '\0') { return game_state_to_json(state); }
    if (strcmp(path, "shape_index") == 0) {
        return cJSON_CreateString(game_state_shape_name(state->shape_index));
    }
    if (strcmp(path, "render_mode_index") == 0) {
        return cJSON_CreateString(game_state_render_mode_name(state->render_mode_index));
    }
    if (strcmp(path, "camera_distance") == 0) {
        return cJSON_CreateNumber((double)state->camera_distance);
    }
    if (strcmp(path, "test_ui_clicks") == 0) {
        return cJSON_CreateNumber(state->test_ui_clicks);
    }
    if (strcmp(path, "test_label_text") == 0) {
        return cJSON_CreateString(state->test_label_text);
    }
    if (strcmp(path, "test_button_text") == 0) {
        return cJSON_CreateString(state->test_button_text);
    }
    if (strcmp(path, "tutorial.done") == 0) {
        return cJSON_CreateBool(state->tutorial_done);
    }
    if (strcmp(path, "wallet.soft") == 0) {
        return cJSON_CreateString(gsj_i64_to_string(state->wallet_soft, (char[21]){0}, 21));
    }
    if (strcmp(path, "wallet.hard") == 0) {
        return cJSON_CreateString(gsj_i64_to_string(state->wallet_hard, (char[21]){0}, 21));
    }
    if (strcmp(path, "equipment.hand_item_id") == 0) {
        return state->has_equipment_hand_item_id ? cJSON_CreateString(state->equipment_hand_item_id) : cJSON_CreateNull();
    }
    if (strcmp(path, "hero.level") == 0) {
        return cJSON_CreateNumber(state->hero_level);
    }
    if (strcmp(path, "hero.xp") == 0) {
        return cJSON_CreateNumber(state->hero_xp);
    }
    if (strcmp(path, "hero.hp") == 0) {
        return cJSON_CreateNumber(state->hero_hp);
    }
    if (strcmp(path, "hero.hp_max") == 0) {
        return cJSON_CreateNumber(state->hero_hp_max);
    }
    if (strcmp(path, "hero.attack") == 0) {
        return cJSON_CreateNumber(state->hero_attack);
    }
    if (strcmp(path, "hero.defense") == 0) {
        return cJSON_CreateNumber(state->hero_defense);
    }
    if (strcmp(path, "hero.gold") == 0) {
        return cJSON_CreateNumber(state->hero_gold);
    }
    if (strcmp(path, "location_index") == 0) {
        return cJSON_CreateString(game_state_location_name(state->location_index));
    }
    if (strcmp(path, "quest_stage_index") == 0) {
        return cJSON_CreateString(game_state_quest_stage_name(state->quest_stage_index));
    }
    if (strcmp(path, "battle_state_index") == 0) {
        return cJSON_CreateString(game_state_battle_state_name(state->battle_state_index));
    }
    if (strcmp(path, "battle.round") == 0) {
        return cJSON_CreateNumber(state->battle_round);
    }
    if (strcmp(path, "battle.enemy_hp") == 0) {
        return cJSON_CreateNumber(state->battle_enemy_hp);
    }
    if (strcmp(path, "battle.enemy_hp_max") == 0) {
        return cJSON_CreateNumber(state->battle_enemy_hp_max);
    }
    if (strcmp(path, "battle.enemy_attack") == 0) {
        return cJSON_CreateNumber(state->battle_enemy_attack);
    }
    if (strcmp(path, "battle.enemy_defense") == 0) {
        return cJSON_CreateNumber(state->battle_enemy_defense);
    }
    if (strcmp(path, "battle.last_damage") == 0) {
        return cJSON_CreateNumber(state->battle_last_damage);
    }
    if (strcmp(path, "battle.last_enemy_damage") == 0) {
        return cJSON_CreateNumber(state->battle_last_enemy_damage);
    }
    if (strcmp(path, "battle.wins") == 0) {
        return cJSON_CreateNumber(state->battle_wins);
    }
    if (strcmp(path, "quest.wolf_kills") == 0) {
        return cJSON_CreateNumber(state->quest_wolf_kills);
    }
    if (strcmp(path, "reward.pending") == 0) {
        return cJSON_CreateBool(state->reward_pending);
    }
    if (strcmp(path, "reward.item_ready") == 0) {
        return cJSON_CreateBool(state->reward_item_ready);
    }
    if (strcmp(path, "gear.ring_equipped") == 0) {
        return cJSON_CreateBool(state->gear_ring_equipped);
    }
    if (strcmp(path, "old_mine.scouted") == 0) {
        return cJSON_CreateBool(state->old_mine_scouted);
    }
    if (strcmp(path, "old_mine.depth") == 0) {
        return cJSON_CreateNumber(state->old_mine_depth);
    }
    if (strcmp(path, "old_mine.ember_shards") == 0) {
        return cJSON_CreateNumber(state->old_mine_ember_shards);
    }
    if (strcmp(path, "old_mine.depth_resolved") == 0) {
        return cJSON_CreateBool(state->old_mine_depth_resolved);
    }
    if (strcmp(path, "old_mine.bat_defeated") == 0) {
        return cJSON_CreateBool(state->old_mine_bat_defeated);
    }
    if (strcmp(path, "old_mine.bat_damage") == 0) {
        return cJSON_CreateNumber(state->old_mine_bat_damage);
    }
    if (strcmp(path, "old_mine.depth_gold") == 0) {
        return cJSON_CreateNumber(state->old_mine_depth_gold);
    }
    if (strcmp(path, "old_mine.delve_count") == 0) {
        return cJSON_CreateNumber(state->old_mine_delve_count);
    }
    if (strcmp(path, "old_mine.cache_claimed") == 0) {
        return cJSON_CreateBool(state->old_mine_cache_claimed);
    }
    if (strcmp(path, "old_mine.last_delve_shards") == 0) {
        return cJSON_CreateNumber(state->old_mine_last_delve_shards);
    }
    if (strcmp(path, "old_mine.last_delve_gold") == 0) {
        return cJSON_CreateNumber(state->old_mine_last_delve_gold);
    }
    if (strcmp(path, "old_mine.last_delve_xp") == 0) {
        return cJSON_CreateNumber(state->old_mine_last_delve_xp);
    }
    if (strcmp(path, "gear.mine_lantern") == 0) {
        return cJSON_CreateBool(state->gear_mine_lantern);
    }
    if (strcmp(path, "old_mine.depth2_unlocked") == 0) {
        return cJSON_CreateBool(state->old_mine_depth2_unlocked);
    }
    if (strcmp(path, "inventory.item_ids") == 0) {
        return inventory_item_ids_to_json(state);
    }
    if (strcmp(path, "items") == 0) {
        return items_to_json(state);
    }
    if (strncmp(path, "items.", 6) == 0) {
        const char *key = path + 6;
        const char *field = strchr(key, '.');
        char map_key[GAME_STATE_STRING_MAX];
        if (field) {
            size_t len = (size_t)(field - key);
            if (len == 0 || len >= sizeof(map_key)) { gsj_set_error(error, error_cap, "bad map key"); return NULL; }
            memcpy(map_key, key, len);
            map_key[len] = '\0';
            field++;
        } else if (!gsj_copy_text(map_key, sizeof(map_key), key)) {
            gsj_set_error(error, error_cap, "bad map key");
            return NULL;
        }
        const GameItemInstance *obj = find_items_const(state, map_key);
        if (!obj) { gsj_set_error(error, error_cap, "unknown map key"); return NULL; }
        return item_instance_get_field_json(obj, field, error, error_cap);
    }
    gsj_set_error(error, error_cap, "unknown state path");
    return NULL;
}

bool game_state_set_path_json(GameState *state, const char *path, const cJSON *value, char *error, int error_cap) {
    if (!state || !path || !path[0] || !value) { gsj_set_error(error, error_cap, "path and value are required"); return false; }
    if (strcmp(path, "shape_index") == 0) {
        if (!gsj_parse_enum_value(value, k_shape_names, GAME_STATE_SHAPE_COUNT, &state->shape_index, error, error_cap)) { return false; }
        return true;
    }
    if (strcmp(path, "render_mode_index") == 0) {
        if (!gsj_parse_enum_value(value, k_render_mode_names, GAME_STATE_RENDER_MODE_COUNT, &state->render_mode_index, error, error_cap)) { return false; }
        return true;
    }
    if (strcmp(path, "camera_distance") == 0) {
        if (!cJSON_IsNumber(value)) { gsj_set_error(error, error_cap, "expected number"); return false; }
        float parsed = (float)value->valuedouble;
        if (parsed < GAME_STATE_CAMERA_DISTANCE_MIN || parsed > GAME_STATE_CAMERA_DISTANCE_MAX) { gsj_set_error(error, error_cap, "number out of range"); return false; }
        state->camera_distance = parsed;
        return true;
    }
    if (strcmp(path, "test_ui_clicks") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_TEST_UI_CLICKS_MIN, GAME_STATE_TEST_UI_CLICKS_MAX, &parsed, error, error_cap)) { return false; }
        state->test_ui_clicks = parsed;
        return true;
    }
    if (strcmp(path, "test_label_text") == 0) {
        if (!cJSON_IsString(value) || !gsj_copy_text(state->test_label_text, sizeof(state->test_label_text), value->valuestring)) { gsj_set_error(error, error_cap, "expected short string"); return false; }
        return true;
    }
    if (strcmp(path, "test_button_text") == 0) {
        if (!cJSON_IsString(value) || !gsj_copy_text(state->test_button_text, sizeof(state->test_button_text), value->valuestring)) { gsj_set_error(error, error_cap, "expected short string"); return false; }
        return true;
    }
    if (strcmp(path, "tutorial.done") == 0) {
        if (!cJSON_IsBool(value)) { gsj_set_error(error, error_cap, "expected bool"); return false; }
        state->tutorial_done = cJSON_IsTrue(value);
        return true;
    }
    if (strcmp(path, "wallet.soft") == 0) {
        if (!gsj_parse_i64_value(value, GAME_STATE_WALLET_SOFT_MIN, GAME_STATE_WALLET_SOFT_MAX, &state->wallet_soft, error, error_cap)) { return false; }
        return true;
    }
    if (strcmp(path, "wallet.hard") == 0) {
        if (!gsj_parse_i64_value(value, GAME_STATE_WALLET_HARD_MIN, GAME_STATE_WALLET_HARD_MAX, &state->wallet_hard, error, error_cap)) { return false; }
        return true;
    }
    if (strcmp(path, "equipment.hand_item_id") == 0) {
        if (cJSON_IsNull(value)) {
            state->has_equipment_hand_item_id = false;
            state->equipment_hand_item_id[0] = '\0';
            return true;
        }
        if (!cJSON_IsString(value) || !gsj_copy_text(state->equipment_hand_item_id, sizeof(state->equipment_hand_item_id), value->valuestring)) { gsj_set_error(error, error_cap, "expected short string or null"); return false; }
        state->has_equipment_hand_item_id = true;
        return true;
    }
    if (strcmp(path, "hero.level") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_HERO_LEVEL_MIN, GAME_STATE_HERO_LEVEL_MAX, &parsed, error, error_cap)) { return false; }
        state->hero_level = parsed;
        return true;
    }
    if (strcmp(path, "hero.xp") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_HERO_XP_MIN, GAME_STATE_HERO_XP_MAX, &parsed, error, error_cap)) { return false; }
        state->hero_xp = parsed;
        return true;
    }
    if (strcmp(path, "hero.hp") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_HERO_HP_MIN, GAME_STATE_HERO_HP_MAX, &parsed, error, error_cap)) { return false; }
        state->hero_hp = parsed;
        return true;
    }
    if (strcmp(path, "hero.hp_max") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_HERO_HP_MAX_MIN, GAME_STATE_HERO_HP_MAX_MAX, &parsed, error, error_cap)) { return false; }
        state->hero_hp_max = parsed;
        return true;
    }
    if (strcmp(path, "hero.attack") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_HERO_ATTACK_MIN, GAME_STATE_HERO_ATTACK_MAX, &parsed, error, error_cap)) { return false; }
        state->hero_attack = parsed;
        return true;
    }
    if (strcmp(path, "hero.defense") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_HERO_DEFENSE_MIN, GAME_STATE_HERO_DEFENSE_MAX, &parsed, error, error_cap)) { return false; }
        state->hero_defense = parsed;
        return true;
    }
    if (strcmp(path, "hero.gold") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_HERO_GOLD_MIN, GAME_STATE_HERO_GOLD_MAX, &parsed, error, error_cap)) { return false; }
        state->hero_gold = parsed;
        return true;
    }
    if (strcmp(path, "location_index") == 0) {
        if (!gsj_parse_enum_value(value, k_location_names, GAME_STATE_LOCATION_COUNT, &state->location_index, error, error_cap)) { return false; }
        return true;
    }
    if (strcmp(path, "quest_stage_index") == 0) {
        if (!gsj_parse_enum_value(value, k_quest_stage_names, GAME_STATE_QUEST_STAGE_COUNT, &state->quest_stage_index, error, error_cap)) { return false; }
        return true;
    }
    if (strcmp(path, "battle_state_index") == 0) {
        if (!gsj_parse_enum_value(value, k_battle_state_names, GAME_STATE_BATTLE_STATE_COUNT, &state->battle_state_index, error, error_cap)) { return false; }
        return true;
    }
    if (strcmp(path, "battle.round") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_BATTLE_ROUND_MIN, GAME_STATE_BATTLE_ROUND_MAX, &parsed, error, error_cap)) { return false; }
        state->battle_round = parsed;
        return true;
    }
    if (strcmp(path, "battle.enemy_hp") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_BATTLE_ENEMY_HP_MIN, GAME_STATE_BATTLE_ENEMY_HP_MAX, &parsed, error, error_cap)) { return false; }
        state->battle_enemy_hp = parsed;
        return true;
    }
    if (strcmp(path, "battle.enemy_hp_max") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_BATTLE_ENEMY_HP_MAX_MIN, GAME_STATE_BATTLE_ENEMY_HP_MAX_MAX, &parsed, error, error_cap)) { return false; }
        state->battle_enemy_hp_max = parsed;
        return true;
    }
    if (strcmp(path, "battle.enemy_attack") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_BATTLE_ENEMY_ATTACK_MIN, GAME_STATE_BATTLE_ENEMY_ATTACK_MAX, &parsed, error, error_cap)) { return false; }
        state->battle_enemy_attack = parsed;
        return true;
    }
    if (strcmp(path, "battle.enemy_defense") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_BATTLE_ENEMY_DEFENSE_MIN, GAME_STATE_BATTLE_ENEMY_DEFENSE_MAX, &parsed, error, error_cap)) { return false; }
        state->battle_enemy_defense = parsed;
        return true;
    }
    if (strcmp(path, "battle.last_damage") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_BATTLE_LAST_DAMAGE_MIN, GAME_STATE_BATTLE_LAST_DAMAGE_MAX, &parsed, error, error_cap)) { return false; }
        state->battle_last_damage = parsed;
        return true;
    }
    if (strcmp(path, "battle.last_enemy_damage") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_BATTLE_LAST_ENEMY_DAMAGE_MIN, GAME_STATE_BATTLE_LAST_ENEMY_DAMAGE_MAX, &parsed, error, error_cap)) { return false; }
        state->battle_last_enemy_damage = parsed;
        return true;
    }
    if (strcmp(path, "battle.wins") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_BATTLE_WINS_MIN, GAME_STATE_BATTLE_WINS_MAX, &parsed, error, error_cap)) { return false; }
        state->battle_wins = parsed;
        return true;
    }
    if (strcmp(path, "quest.wolf_kills") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_QUEST_WOLF_KILLS_MIN, GAME_STATE_QUEST_WOLF_KILLS_MAX, &parsed, error, error_cap)) { return false; }
        state->quest_wolf_kills = parsed;
        return true;
    }
    if (strcmp(path, "reward.pending") == 0) {
        if (!cJSON_IsBool(value)) { gsj_set_error(error, error_cap, "expected bool"); return false; }
        state->reward_pending = cJSON_IsTrue(value);
        return true;
    }
    if (strcmp(path, "reward.item_ready") == 0) {
        if (!cJSON_IsBool(value)) { gsj_set_error(error, error_cap, "expected bool"); return false; }
        state->reward_item_ready = cJSON_IsTrue(value);
        return true;
    }
    if (strcmp(path, "gear.ring_equipped") == 0) {
        if (!cJSON_IsBool(value)) { gsj_set_error(error, error_cap, "expected bool"); return false; }
        state->gear_ring_equipped = cJSON_IsTrue(value);
        return true;
    }
    if (strcmp(path, "old_mine.scouted") == 0) {
        if (!cJSON_IsBool(value)) { gsj_set_error(error, error_cap, "expected bool"); return false; }
        state->old_mine_scouted = cJSON_IsTrue(value);
        return true;
    }
    if (strcmp(path, "old_mine.depth") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_OLD_MINE_DEPTH_MIN, GAME_STATE_OLD_MINE_DEPTH_MAX, &parsed, error, error_cap)) { return false; }
        state->old_mine_depth = parsed;
        return true;
    }
    if (strcmp(path, "old_mine.ember_shards") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_OLD_MINE_EMBER_SHARDS_MIN, GAME_STATE_OLD_MINE_EMBER_SHARDS_MAX, &parsed, error, error_cap)) { return false; }
        state->old_mine_ember_shards = parsed;
        return true;
    }
    if (strcmp(path, "old_mine.depth_resolved") == 0) {
        if (!cJSON_IsBool(value)) { gsj_set_error(error, error_cap, "expected bool"); return false; }
        state->old_mine_depth_resolved = cJSON_IsTrue(value);
        return true;
    }
    if (strcmp(path, "old_mine.bat_defeated") == 0) {
        if (!cJSON_IsBool(value)) { gsj_set_error(error, error_cap, "expected bool"); return false; }
        state->old_mine_bat_defeated = cJSON_IsTrue(value);
        return true;
    }
    if (strcmp(path, "old_mine.bat_damage") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_OLD_MINE_BAT_DAMAGE_MIN, GAME_STATE_OLD_MINE_BAT_DAMAGE_MAX, &parsed, error, error_cap)) { return false; }
        state->old_mine_bat_damage = parsed;
        return true;
    }
    if (strcmp(path, "old_mine.depth_gold") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_OLD_MINE_DEPTH_GOLD_MIN, GAME_STATE_OLD_MINE_DEPTH_GOLD_MAX, &parsed, error, error_cap)) { return false; }
        state->old_mine_depth_gold = parsed;
        return true;
    }
    if (strcmp(path, "old_mine.delve_count") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_OLD_MINE_DELVE_COUNT_MIN, GAME_STATE_OLD_MINE_DELVE_COUNT_MAX, &parsed, error, error_cap)) { return false; }
        state->old_mine_delve_count = parsed;
        return true;
    }
    if (strcmp(path, "old_mine.cache_claimed") == 0) {
        if (!cJSON_IsBool(value)) { gsj_set_error(error, error_cap, "expected bool"); return false; }
        state->old_mine_cache_claimed = cJSON_IsTrue(value);
        return true;
    }
    if (strcmp(path, "old_mine.last_delve_shards") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_OLD_MINE_LAST_DELVE_SHARDS_MIN, GAME_STATE_OLD_MINE_LAST_DELVE_SHARDS_MAX, &parsed, error, error_cap)) { return false; }
        state->old_mine_last_delve_shards = parsed;
        return true;
    }
    if (strcmp(path, "old_mine.last_delve_gold") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_OLD_MINE_LAST_DELVE_GOLD_MIN, GAME_STATE_OLD_MINE_LAST_DELVE_GOLD_MAX, &parsed, error, error_cap)) { return false; }
        state->old_mine_last_delve_gold = parsed;
        return true;
    }
    if (strcmp(path, "old_mine.last_delve_xp") == 0) {
        int parsed = 0;
        if (!gsj_parse_int_value(value, GAME_STATE_OLD_MINE_LAST_DELVE_XP_MIN, GAME_STATE_OLD_MINE_LAST_DELVE_XP_MAX, &parsed, error, error_cap)) { return false; }
        state->old_mine_last_delve_xp = parsed;
        return true;
    }
    if (strcmp(path, "gear.mine_lantern") == 0) {
        if (!cJSON_IsBool(value)) { gsj_set_error(error, error_cap, "expected bool"); return false; }
        state->gear_mine_lantern = cJSON_IsTrue(value);
        return true;
    }
    if (strcmp(path, "old_mine.depth2_unlocked") == 0) {
        if (!cJSON_IsBool(value)) { gsj_set_error(error, error_cap, "expected bool"); return false; }
        state->old_mine_depth2_unlocked = cJSON_IsTrue(value);
        return true;
    }
    if (strcmp(path, "inventory.item_ids") == 0) {
        return set_inventory_item_ids_from_json(state, value, error, error_cap);
    }
    if (strcmp(path, "items") == 0) {
        return set_items_from_json(state, value, error, error_cap);
    }
    if (strncmp(path, "items.", 6) == 0) {
        const char *key = path + 6;
        const char *field = strchr(key, '.');
        char map_key[GAME_STATE_STRING_MAX];
        if (field) {
            size_t len = (size_t)(field - key);
            if (len == 0 || len >= sizeof(map_key)) { gsj_set_error(error, error_cap, "bad map key"); return false; }
            memcpy(map_key, key, len);
            map_key[len] = '\0';
            field++;
        } else if (!gsj_copy_text(map_key, sizeof(map_key), key)) {
            gsj_set_error(error, error_cap, "bad map key");
            return false;
        }
        GameItemInstance *obj = alloc_items(state, map_key);
        if (!obj) { gsj_set_error(error, error_cap, "too many map entries or long key"); return false; }
        return field ? item_instance_set_field_json(obj, field, value, error, error_cap) : item_instance_from_json(obj, value, error, error_cap);
    }
    gsj_set_error(error, error_cap, "unknown state path");
    return false;
}

bool game_state_patch_json(GameState *state, const cJSON *values, char *error, int error_cap) {
    if (!cJSON_IsObject(values)) { gsj_set_error(error, error_cap, "values must be an object"); return false; }
    GameState next = *state;
    const cJSON *item = NULL;
    cJSON_ArrayForEach(item, values) {
        if (!item->string || !game_state_set_path_json(&next, item->string, item, error, error_cap)) { return false; }
    }
    if (!game_state_validate(&next, error, error_cap)) { return false; }
    *state = next;
    return true;
}

bool game_state_from_json(GameState *state, const cJSON *json, char *error, int error_cap) {
    if (!cJSON_IsObject(json)) { gsj_set_error(error, error_cap, "state json must be object"); return false; }
    GameState next;
    game_state_init_defaults(&next);
    if (!gsj_read_enum(json, "shape_index", k_shape_names, GAME_STATE_SHAPE_COUNT, &(&next)->shape_index, error, error_cap)) { return false; }
    if (!gsj_read_enum(json, "render_mode_index", k_render_mode_names, GAME_STATE_RENDER_MODE_COUNT, &(&next)->render_mode_index, error, error_cap)) { return false; }
    if (!gsj_read_float_range(json, "camera_distance", GAME_STATE_CAMERA_DISTANCE_MIN, GAME_STATE_CAMERA_DISTANCE_MAX, &(&next)->camera_distance, error, error_cap)) { return false; }
    if (!gsj_read_int_range(json, "test_ui_clicks", GAME_STATE_TEST_UI_CLICKS_MIN, GAME_STATE_TEST_UI_CLICKS_MAX, &(&next)->test_ui_clicks, error, error_cap)) { return false; }
    if (!gsj_read_string(json, "test_label_text", (&next)->test_label_text, sizeof((&next)->test_label_text), error, error_cap)) { return false; }
    if (!gsj_read_string(json, "test_button_text", (&next)->test_button_text, sizeof((&next)->test_button_text), error, error_cap)) { return false; }
    const cJSON *tutorial = gsj_object_item(json, "tutorial");
    if (!gsj_read_bool(tutorial, "done", &(&next)->tutorial_done, error, error_cap)) { return false; }
    const cJSON *wallet = gsj_object_item(json, "wallet");
    if (!gsj_read_i64(wallet, "soft", GAME_STATE_WALLET_SOFT_MIN, GAME_STATE_WALLET_SOFT_MAX, &(&next)->wallet_soft, error, error_cap)) { return false; }
    if (!gsj_read_i64(wallet, "hard", GAME_STATE_WALLET_HARD_MIN, GAME_STATE_WALLET_HARD_MAX, &(&next)->wallet_hard, error, error_cap)) { return false; }
    const cJSON *items_json = gsj_object_item(json, "items");
    if (items_json && !set_items_from_json(&next, items_json, error, error_cap)) {
        return false;
    }
    const cJSON *inventory = gsj_object_item(json, "inventory");
    const cJSON *inventory_item_ids_json = gsj_object_item(inventory, "item_ids");
    if (inventory_item_ids_json && !set_inventory_item_ids_from_json(&next, inventory_item_ids_json, error, error_cap)) {
        return false;
    }
    const cJSON *equipment = gsj_object_item(json, "equipment");
    const cJSON *equipment_hand_item_id = gsj_object_item(equipment, "hand_item_id");
    if (equipment_hand_item_id) {
        if (cJSON_IsNull(equipment_hand_item_id)) {
            (&next)->has_equipment_hand_item_id = false;
        } else if (cJSON_IsString(equipment_hand_item_id) && gsj_copy_text((&next)->equipment_hand_item_id, sizeof((&next)->equipment_hand_item_id), equipment_hand_item_id->valuestring)) {
            (&next)->has_equipment_hand_item_id = true;
        } else {
            gsj_set_error(error, error_cap, "expected short string or null");
            return false;
        }
    }
    const cJSON *hero = gsj_object_item(json, "hero");
    if (!gsj_read_int_range(hero, "level", GAME_STATE_HERO_LEVEL_MIN, GAME_STATE_HERO_LEVEL_MAX, &(&next)->hero_level, error, error_cap)) { return false; }
    if (!gsj_read_int_range(hero, "xp", GAME_STATE_HERO_XP_MIN, GAME_STATE_HERO_XP_MAX, &(&next)->hero_xp, error, error_cap)) { return false; }
    if (!gsj_read_int_range(hero, "hp", GAME_STATE_HERO_HP_MIN, GAME_STATE_HERO_HP_MAX, &(&next)->hero_hp, error, error_cap)) { return false; }
    if (!gsj_read_int_range(hero, "hp_max", GAME_STATE_HERO_HP_MAX_MIN, GAME_STATE_HERO_HP_MAX_MAX, &(&next)->hero_hp_max, error, error_cap)) { return false; }
    if (!gsj_read_int_range(hero, "attack", GAME_STATE_HERO_ATTACK_MIN, GAME_STATE_HERO_ATTACK_MAX, &(&next)->hero_attack, error, error_cap)) { return false; }
    if (!gsj_read_int_range(hero, "defense", GAME_STATE_HERO_DEFENSE_MIN, GAME_STATE_HERO_DEFENSE_MAX, &(&next)->hero_defense, error, error_cap)) { return false; }
    if (!gsj_read_int_range(hero, "gold", GAME_STATE_HERO_GOLD_MIN, GAME_STATE_HERO_GOLD_MAX, &(&next)->hero_gold, error, error_cap)) { return false; }
    if (!gsj_read_enum(json, "location_index", k_location_names, GAME_STATE_LOCATION_COUNT, &(&next)->location_index, error, error_cap)) { return false; }
    if (!gsj_read_enum(json, "quest_stage_index", k_quest_stage_names, GAME_STATE_QUEST_STAGE_COUNT, &(&next)->quest_stage_index, error, error_cap)) { return false; }
    if (!gsj_read_enum(json, "battle_state_index", k_battle_state_names, GAME_STATE_BATTLE_STATE_COUNT, &(&next)->battle_state_index, error, error_cap)) { return false; }
    const cJSON *battle = gsj_object_item(json, "battle");
    if (!gsj_read_int_range(battle, "round", GAME_STATE_BATTLE_ROUND_MIN, GAME_STATE_BATTLE_ROUND_MAX, &(&next)->battle_round, error, error_cap)) { return false; }
    if (!gsj_read_int_range(battle, "enemy_hp", GAME_STATE_BATTLE_ENEMY_HP_MIN, GAME_STATE_BATTLE_ENEMY_HP_MAX, &(&next)->battle_enemy_hp, error, error_cap)) { return false; }
    if (!gsj_read_int_range(battle, "enemy_hp_max", GAME_STATE_BATTLE_ENEMY_HP_MAX_MIN, GAME_STATE_BATTLE_ENEMY_HP_MAX_MAX, &(&next)->battle_enemy_hp_max, error, error_cap)) { return false; }
    if (!gsj_read_int_range(battle, "enemy_attack", GAME_STATE_BATTLE_ENEMY_ATTACK_MIN, GAME_STATE_BATTLE_ENEMY_ATTACK_MAX, &(&next)->battle_enemy_attack, error, error_cap)) { return false; }
    if (!gsj_read_int_range(battle, "enemy_defense", GAME_STATE_BATTLE_ENEMY_DEFENSE_MIN, GAME_STATE_BATTLE_ENEMY_DEFENSE_MAX, &(&next)->battle_enemy_defense, error, error_cap)) { return false; }
    if (!gsj_read_int_range(battle, "last_damage", GAME_STATE_BATTLE_LAST_DAMAGE_MIN, GAME_STATE_BATTLE_LAST_DAMAGE_MAX, &(&next)->battle_last_damage, error, error_cap)) { return false; }
    if (!gsj_read_int_range(battle, "last_enemy_damage", GAME_STATE_BATTLE_LAST_ENEMY_DAMAGE_MIN, GAME_STATE_BATTLE_LAST_ENEMY_DAMAGE_MAX, &(&next)->battle_last_enemy_damage, error, error_cap)) { return false; }
    if (!gsj_read_int_range(battle, "wins", GAME_STATE_BATTLE_WINS_MIN, GAME_STATE_BATTLE_WINS_MAX, &(&next)->battle_wins, error, error_cap)) { return false; }
    const cJSON *quest = gsj_object_item(json, "quest");
    if (!gsj_read_int_range(quest, "wolf_kills", GAME_STATE_QUEST_WOLF_KILLS_MIN, GAME_STATE_QUEST_WOLF_KILLS_MAX, &(&next)->quest_wolf_kills, error, error_cap)) { return false; }
    const cJSON *reward = gsj_object_item(json, "reward");
    if (!gsj_read_bool(reward, "pending", &(&next)->reward_pending, error, error_cap)) { return false; }
    if (!gsj_read_bool(reward, "item_ready", &(&next)->reward_item_ready, error, error_cap)) { return false; }
    const cJSON *gear = gsj_object_item(json, "gear");
    if (!gsj_read_bool(gear, "ring_equipped", &(&next)->gear_ring_equipped, error, error_cap)) { return false; }
    const cJSON *old_mine = gsj_object_item(json, "old_mine");
    if (!gsj_read_bool(old_mine, "scouted", &(&next)->old_mine_scouted, error, error_cap)) { return false; }
    if (!gsj_read_int_range(old_mine, "depth", GAME_STATE_OLD_MINE_DEPTH_MIN, GAME_STATE_OLD_MINE_DEPTH_MAX, &(&next)->old_mine_depth, error, error_cap)) { return false; }
    if (!gsj_read_int_range(old_mine, "ember_shards", GAME_STATE_OLD_MINE_EMBER_SHARDS_MIN, GAME_STATE_OLD_MINE_EMBER_SHARDS_MAX, &(&next)->old_mine_ember_shards, error, error_cap)) { return false; }
    if (!gsj_read_bool(old_mine, "depth_resolved", &(&next)->old_mine_depth_resolved, error, error_cap)) { return false; }
    if (!gsj_read_bool(old_mine, "bat_defeated", &(&next)->old_mine_bat_defeated, error, error_cap)) { return false; }
    if (!gsj_read_int_range(old_mine, "bat_damage", GAME_STATE_OLD_MINE_BAT_DAMAGE_MIN, GAME_STATE_OLD_MINE_BAT_DAMAGE_MAX, &(&next)->old_mine_bat_damage, error, error_cap)) { return false; }
    if (!gsj_read_int_range(old_mine, "depth_gold", GAME_STATE_OLD_MINE_DEPTH_GOLD_MIN, GAME_STATE_OLD_MINE_DEPTH_GOLD_MAX, &(&next)->old_mine_depth_gold, error, error_cap)) { return false; }
    if (!gsj_read_int_range(old_mine, "delve_count", GAME_STATE_OLD_MINE_DELVE_COUNT_MIN, GAME_STATE_OLD_MINE_DELVE_COUNT_MAX, &(&next)->old_mine_delve_count, error, error_cap)) { return false; }
    if (!gsj_read_bool(old_mine, "cache_claimed", &(&next)->old_mine_cache_claimed, error, error_cap)) { return false; }
    if (!gsj_read_int_range(old_mine, "last_delve_shards", GAME_STATE_OLD_MINE_LAST_DELVE_SHARDS_MIN, GAME_STATE_OLD_MINE_LAST_DELVE_SHARDS_MAX, &(&next)->old_mine_last_delve_shards, error, error_cap)) { return false; }
    if (!gsj_read_int_range(old_mine, "last_delve_gold", GAME_STATE_OLD_MINE_LAST_DELVE_GOLD_MIN, GAME_STATE_OLD_MINE_LAST_DELVE_GOLD_MAX, &(&next)->old_mine_last_delve_gold, error, error_cap)) { return false; }
    if (!gsj_read_int_range(old_mine, "last_delve_xp", GAME_STATE_OLD_MINE_LAST_DELVE_XP_MIN, GAME_STATE_OLD_MINE_LAST_DELVE_XP_MAX, &(&next)->old_mine_last_delve_xp, error, error_cap)) { return false; }
    if (!gsj_read_bool(gear, "mine_lantern", &(&next)->gear_mine_lantern, error, error_cap)) { return false; }
    if (!gsj_read_bool(old_mine, "depth2_unlocked", &(&next)->old_mine_depth2_unlocked, error, error_cap)) { return false; }
    if (!game_state_validate(&next, error, error_cap)) { return false; }
    *state = next;
    return true;
}

static void   frag_reset(void)                                             { game_state_init_defaults(&game_state); }
static cJSON *frag_to_json(void)                                           { return game_state_to_json(&game_state); }
static bool   frag_from_json(const cJSON *j, char *e, int c)               { return game_state_from_json(&game_state, j, e, c); }
static cJSON *frag_get_path(const char *s, char *e, int c)                 { return game_state_get_path_json(&game_state, s, e, c); }
static bool   frag_set_path(const char *s, const cJSON *v, char *e, int c) { return game_state_set_path_json(&game_state, s, v, e, c); }
static cJSON *frag_schema(void)                                            { return game_state_schema_json(); }

const GameSaveFragment game_state_fragment = {
    .id            = GAME_STATE_FRAGMENT_ID,
    .version       = GAME_STATE_VERSION,
    .steps         = NULL,
    .reset         = frag_reset,
    .on_new_game   = NULL,
    .to_json       = frag_to_json,
    .from_json     = frag_from_json,
    .reconcile     = NULL,
    .get_path_json = frag_get_path,
    .set_path_json = frag_set_path,
    .schema_json   = frag_schema,
};
