#ifndef GAME_STATE_EVENTS_GEN_H
#define GAME_STATE_EVENTS_GEN_H

/* Generated by features/game-state/scripts/generate_state.py from state/game_state.schema.json. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "hash/nt_hash.h"    /* nt_hash64_t */
#include "game_event_desc.h" /* game_event_desc_t + field-type enum */

/* ---- game.shape_changed ---- */
typedef struct GameEvShapeChanged {
    int32_t from_index;
    int32_t to_index;
    uint32_t note; /* byte offset -> inline NUL string (read via accessor) */
} GameEvShapeChanged;

nt_hash64_t game_ev_shape_changed_type(void); /* nt_hash64_str("game.shape_changed"), cached */

const void *game_emit_shape_changed(int32_t from_index, int32_t to_index, const char *note);

static inline const char *game_ev_shape_changed_note(const GameEvShapeChanged *e) {
    return (const char *)e + e->note;
}

extern const game_event_desc_t game_ev_shape_changed_desc;

/* ---- fragment event table + label registration ---- */
extern const game_event_desc_t *const game_ev_descs[];
extern const int game_ev_desc_count;

void game_ev_register(void); /* register debug labels; call once after nt_hash_init */

#endif /* GAME_STATE_EVENTS_GEN_H */
