set(CMAKE_C_STANDARD 17)
set(CMAKE_C_STANDARD_REQUIRED ON)

# Two-build convention: the human build (native-debug, VS Code) has no DevAPI;
# agents configure their own dir (build/devapi-debug) with -DGAME_DEVAPI_ENABLED=ON
# and get a distinct window title so both can run side by side.
if(NOT DEFINED GAME_DEVAPI_ENABLED)
    set(GAME_DEVAPI_ENABLED OFF CACHE BOOL "Build the template with engine DevAPI automation support." FORCE)
endif()

set(GAME_PUBLISH_TARGET "local" CACHE STRING "Publish target: local, itch, poki, yandex, or playgama.")
option(GAME_AUDIO_BROWSER_SMOKE "Export narrow game_audio controls for a local browser smoke artifact." OFF)
set_property(CACHE GAME_PUBLISH_TARGET PROPERTY STRINGS local itch poki yandex playgama)
if(NOT GAME_PUBLISH_TARGET MATCHES "^(local|itch|poki|yandex|playgama)$")
    message(FATAL_ERROR "GAME_PUBLISH_TARGET must be one of: local, itch, poki, yandex, playgama")
endif()

set(GAME_RUNTIME_BUILD_FINGERPRINT "" CACHE STRING "Target-independent runtime source fingerprint supplied by tools/build_web.mjs.")
string(LENGTH "${GAME_RUNTIME_BUILD_FINGERPRINT}" GAME_RUNTIME_BUILD_FINGERPRINT_LENGTH)
set(GAME_RUNTIME_BUILD_FINGERPRINT_VALID OFF)
if(GAME_RUNTIME_BUILD_FINGERPRINT_LENGTH EQUAL 64 AND GAME_RUNTIME_BUILD_FINGERPRINT MATCHES "^[0-9a-f]+$")
    set(GAME_RUNTIME_BUILD_FINGERPRINT_VALID ON)
endif()
if(GAME_RUNTIME_BUILD_FINGERPRINT AND NOT GAME_RUNTIME_BUILD_FINGERPRINT_VALID)
    message(FATAL_ERROR "GAME_RUNTIME_BUILD_FINGERPRINT must be a lowercase SHA-256 supplied by tools/build_web.mjs.")
endif()
if(EMSCRIPTEN AND NOT GAME_RUNTIME_BUILD_FINGERPRINT_VALID)
    message(FATAL_ERROR "Emscripten builds must be owned by tools/build_web.mjs with a runtime fingerprint.")
endif()

if(EMSCRIPTEN)
    set(_game_default_em_cache "${CMAKE_SOURCE_DIR}/build/emscripten-cache")
    if(DEFINED ENV{EM_CACHE} AND NOT "$ENV{EM_CACHE}" STREQUAL "")
        set(_game_default_em_cache "$ENV{EM_CACHE}")
    endif()
    set(GAME_EMSCRIPTEN_CACHE_DIR "${_game_default_em_cache}" CACHE PATH "Emscripten cache directory for this game checkout.")
    file(MAKE_DIRECTORY "${GAME_EMSCRIPTEN_CACHE_DIR}")
    set(ENV{EM_CACHE} "${GAME_EMSCRIPTEN_CACHE_DIR}")
    set(_game_emcache_launcher "${CMAKE_COMMAND} -E env EM_CACHE=${GAME_EMSCRIPTEN_CACHE_DIR}")
    set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE "${_game_emcache_launcher}")
    set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK "${_game_emcache_launcher}")
endif()

# Preset name must encode the devapi split: engine libs land in
# build/engine/<preset> and build/tools/builder/<preset>, so two builds sharing
# one preset would overwrite each other's engine libs (nt_input with/without
# inject symbols; nt_devapi_web presence) — the parallel-build collision the
# convention exists to prevent. Every web (publish-target x devapi x build-type)
# gets a UNIQUE name, so no combination can alias into another's engine dir.
# Local keeps the legacy wasm preset names because it is the default developer
# path; portal targets append the publish target.
if(EMSCRIPTEN)
    if(GAME_DEVAPI_ENABLED)
        if(CMAKE_BUILD_TYPE STREQUAL "Release")
            set(NT_PRESET_NAME "wasm-devapi-release")
        else()
            set(NT_PRESET_NAME "wasm-devapi-debug")
        endif()
    elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
        set(NT_PRESET_NAME "wasm-release")
    else()
        set(NT_PRESET_NAME "wasm-debug")
    endif()
else()
    if(GAME_DEVAPI_ENABLED)
        if(CMAKE_BUILD_TYPE STREQUAL "Release")
            set(NT_PRESET_NAME "native-devapi-release")
        else()
            set(NT_PRESET_NAME "devapi-debug")
        endif()
    elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
        set(NT_PRESET_NAME "native-release")
    else()
        set(NT_PRESET_NAME "native-debug")
    endif()
endif()
if(EMSCRIPTEN AND NOT GAME_PUBLISH_TARGET STREQUAL "local")
    set(NT_PRESET_NAME "${NT_PRESET_NAME}-${GAME_PUBLISH_TARGET}")
endif()
set(GAME_TITLE "Template" CACHE STRING "Game window title base")
if(GAME_DEVAPI_ENABLED)
    set(GAME_WINDOW_TITLE "${GAME_TITLE} [AI]")
else()
    set(GAME_WINDOW_TITLE "${GAME_TITLE}")
endif()
if(GAME_DEVAPI_ENABLED)
    set(NT_DEVAPI_ENABLED ON CACHE BOOL "Build the engine DevAPI command layer." FORCE)
    set(NT_UI_DEBUG_TOOLS ON CACHE BOOL "Build UI probe data for engine DevAPI ui.* commands." FORCE)
    set(NT_LOG_RING_ENABLED ON CACHE BOOL "Build log ring data for engine DevAPI obs commands." FORCE)
    set(NT_METRICS_ENABLED ON CACHE BOOL "Build metrics data for engine DevAPI obs commands." FORCE)
    set(NT_INTROSPECT_ENABLED ON CACHE BOOL "Build entity introspection for engine DevAPI obs commands." FORCE)
    set(NT_DEVAPI_GROUP_UI ON CACHE BOOL "Build engine DevAPI ui.* commands." FORCE)
    set(NT_DEVAPI_GROUP_OBS ON CACHE BOOL "Build engine DevAPI log/perf/entity/resource commands." FORCE)
    set(NT_DEVAPI_GROUP_CAPTURE ON CACHE BOOL "Build engine DevAPI capture.frame/capture.region commands." FORCE)
else()
    set(NT_DEVAPI_ENABLED OFF CACHE BOOL "Build the engine DevAPI command layer." FORCE)
    foreach(_grp CORE TIME INPUT DISCOVERY UI OBS ENTITY_WRITE CAPTURE)
        set(NT_DEVAPI_GROUP_${_grp} OFF CACHE BOOL "Disabled with GAME_DEVAPI_ENABLED=OFF." FORCE)
    endforeach()
endif()

# E4: GAME_ANALYTICS_ENABLED gates the local analytics writer. A -D override wins (a cache
# entry -> DEFINED -> persists between configures); otherwise the default = GAME_DEVAPI_ENABLED
# as a PLAIN variable (recomputed EVERY configure, so flipping GAME_DEVAPI_ENABLED in a live
# tree updates it -- a CACHE...FORCE default would go stale). NOT CACHE on the default path.
if(NOT DEFINED GAME_ANALYTICS_ENABLED)
    set(GAME_ANALYTICS_ENABLED ${GAME_DEVAPI_ENABLED})
endif()
if(NOT DEFINED GAME_EVENTS_LOG_MIRROR)
    if(CMAKE_BUILD_TYPE STREQUAL "Release")
        set(GAME_EVENTS_LOG_MIRROR OFF)
    else()
        set(GAME_EVENTS_LOG_MIRROR ON)
    endif()
endif()

if(GAME_PUBLISH_TARGET STREQUAL "local")
    set(GAME_PLATFORM_SDK "mock")
    set(GAME_PLATFORM_TARGET_ID 0)
    set(GAME_PLATFORM_SDK_ID 0)
    set(GAME_PLATFORM_EXTERNAL_LINKS_ALLOWED 1)
    set(GAME_PLATFORM_ADS_SUPPORTED 1)
    set(GAME_PLATFORM_REWARDED_SUPPORTED 1)
    set(GAME_PLATFORM_STORAGE_SUPPORTED 1)
elseif(GAME_PUBLISH_TARGET STREQUAL "itch")
    set(GAME_PLATFORM_SDK "mock")
    set(GAME_PLATFORM_TARGET_ID 1)
    set(GAME_PLATFORM_SDK_ID 0)
    set(GAME_PLATFORM_EXTERNAL_LINKS_ALLOWED 1)
    set(GAME_PLATFORM_ADS_SUPPORTED 0)
    set(GAME_PLATFORM_REWARDED_SUPPORTED 0)
    set(GAME_PLATFORM_STORAGE_SUPPORTED 0)
elseif(GAME_PUBLISH_TARGET STREQUAL "poki")
    set(GAME_PLATFORM_SDK "poki")
    set(GAME_PLATFORM_TARGET_ID 2)
    set(GAME_PLATFORM_SDK_ID 1)
    set(GAME_PLATFORM_EXTERNAL_LINKS_ALLOWED 0)
    set(GAME_PLATFORM_ADS_SUPPORTED 1)
    set(GAME_PLATFORM_REWARDED_SUPPORTED 1)
    set(GAME_PLATFORM_STORAGE_SUPPORTED 0)
elseif(GAME_PUBLISH_TARGET STREQUAL "yandex")
    set(GAME_PLATFORM_SDK "yandex")
    set(GAME_PLATFORM_TARGET_ID 3)
    set(GAME_PLATFORM_SDK_ID 2)
    set(GAME_PLATFORM_EXTERNAL_LINKS_ALLOWED 0)
    set(GAME_PLATFORM_ADS_SUPPORTED 1)
    set(GAME_PLATFORM_REWARDED_SUPPORTED 1)
    set(GAME_PLATFORM_STORAGE_SUPPORTED 1)
elseif(GAME_PUBLISH_TARGET STREQUAL "playgama")
    set(GAME_PLATFORM_SDK "playgama")
    set(GAME_PLATFORM_TARGET_ID 4)
    set(GAME_PLATFORM_SDK_ID 3)
    set(GAME_PLATFORM_EXTERNAL_LINKS_ALLOWED 0)
    set(GAME_PLATFORM_ADS_SUPPORTED 1)
    set(GAME_PLATFORM_REWARDED_SUPPORTED 1)
    set(GAME_PLATFORM_STORAGE_SUPPORTED 1)
endif()
if(NOT DEFINED GAME_PLATFORM_SDK_DEBUG_UI)
    if(CMAKE_BUILD_TYPE STREQUAL "Release")
        set(GAME_PLATFORM_SDK_DEBUG_UI OFF)
    else()
        set(GAME_PLATFORM_SDK_DEBUG_UI ON)
    endif()
endif()
if(CMAKE_BUILD_TYPE STREQUAL "Release" AND GAME_PLATFORM_SDK_DEBUG_UI)
    message(FATAL_ERROR "GAME_PLATFORM_SDK_DEBUG_UI must be OFF for Release artifacts.")
endif()
