// Generate .claude/skills/* thin pointers from Codex-discoverable .codex/skills/*.
//
//   node ai_studio/core_harness/agent_surfaces/skills_sync.mjs
//
// Generated files carry a marker line; the script only overwrites files it
// generated, so a hand-written .claude skill is never clobbered.

import { mkdirSync, readdirSync, readFileSync, writeFileSync, existsSync, statSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const args = process.argv.slice(2);

function usage() {
  console.error(`usage:
  node ai_studio/core_harness/agent_surfaces/skills_sync.mjs [--check] [--root <dir>]

Generate .claude/skills/* thin pointers from Codex-discoverable .codex/skills/*.
--check reports drift without writing.`);
  process.exit(2);
}

function takeString(name, fallback) {
  const index = args.indexOf(name);
  if (index === -1) return fallback;
  const value = args[index + 1];
  if (!value || value.startsWith("--")) usage();
  args.splice(index, 2);
  return value;
}

const check = args.includes("--check");
if (check) args.splice(args.indexOf("--check"), 1);
if (args.includes("--help") || args.includes("-h")) usage();

const root = resolve(takeString("--root", fileURLToPath(new URL("../../..", import.meta.url))));
if (args.length > 0) usage();

const srcDir = join(root, ".codex", "skills");
const dstDir = join(root, ".claude", "skills");
const MARKER = "<!-- generated by ai_studio/core_harness/agent_surfaces/skills_sync.mjs; edit .codex/skills instead -->";
// --check: do not write; report drift between .claude/skills and what .codex
// would generate, and exit non-zero if any. This keeps generated pointers from
// silently drifting away from Codex-discoverable .codex/skills.

function parseFrontmatter(text) {
  text = text.replace(/^\uFEFF/, "");
  const lines = text.split(/\r?\n/);
  if (lines[0] !== "---") return {};
  const end = lines.indexOf("---", 1);
  if (end === -1) return {};
  const fields = {};
  let current = null;
  for (const line of lines.slice(1, end)) {
    const m = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (m) {
      current = m[1];
      fields[current] = m[2].trim();
    } else if (current && /^\s+/.test(line)) {
      fields[current] += " " + line.trim();
    }
  }
  for (const k of Object.keys(fields)) {
    fields[k] = fields[k].replace(/^["']|["']$/g, "");
  }
  return fields;
}

function listReferences(skillDir) {
  const refDir = join(skillDir, "references");
  if (!existsSync(refDir)) return [];
  return readdirSync(refDir).filter((f) => f.endsWith(".md"));
}

if (!existsSync(srcDir)) {
  console.error(`error: ${srcDir} not found`);
  process.exit(1);
}

let written = 0;
let removed = 0;
let skipped = 0;
const drift = [];
const seen = new Set();
for (const name of readdirSync(srcDir)) {
  const skillDir = join(srcDir, name);
  const skillFile = join(skillDir, "SKILL.md");
  if (!statSync(skillDir).isDirectory() || !existsSync(skillFile)) continue;
  seen.add(name);

  const fields = parseFrontmatter(readFileSync(skillFile, "utf8"));
  if (!fields.name || !fields.description) {
    console.warn(`warn: ${name}/SKILL.md missing name or description, skipped`);
    continue;
  }

  const outDir = join(dstDir, name);
  const outFile = join(outDir, "SKILL.md");
  if (existsSync(outFile) && !readFileSync(outFile, "utf8").includes(MARKER)) {
    console.log(`skip (hand-written): ${name}`);
    skipped++;
    continue;
  }

  const refs = listReferences(skillDir);
  const refLines = refs.length
    ? ["", "Reference playbooks (load only when the Codex entrypoint says to):", "",
       ...refs.map((r) => `- \`.codex/skills/${name}/references/${r}\``)]
    : [];

  const body = [
    "---",
    `name: ${fields.name}`,
    `description: ${JSON.stringify(fields.description)}`,
    "---",
    MARKER,
    "",
    `# ${fields.name}`,
    "",
    `Codex-discoverable instructions live in \`.codex/skills/${name}/SKILL.md\`.`,
    "Read that file and follow it.",
    ...refLines,
    "",
  ].join("\n");

  if (check) {
    const existing = existsSync(outFile) ? readFileSync(outFile, "utf8") : null;
    if (existing !== body) drift.push(name);
    continue;
  }

  mkdirSync(outDir, { recursive: true });
  writeFileSync(outFile, body);
  console.log(`generated: ${name}`);
  written++;
}

if (existsSync(dstDir)) {
  for (const name of readdirSync(dstDir)) {
    if (seen.has(name)) continue;
    const outDir = join(dstDir, name);
    const outFile = join(outDir, "SKILL.md");
    if (!statSync(outDir).isDirectory() || !existsSync(outFile)) continue;
    const text = readFileSync(outFile, "utf8");
    if (!text.includes(MARKER)) {
      skipped++;
      continue;
    }
    if (check) {
      drift.push(name);
      continue;
    }
    rmSync(outDir, { recursive: true, force: true });
    console.log(`removed stale generated pointer: ${name}`);
    removed++;
  }
}

if (check) {
  if (drift.length) {
    console.error(`skills drift: ${drift.length} .claude/skills pointer(s) out of sync with .codex/skills: ${drift.join(", ")}`);
    console.error("fix: run `node ai_studio/core_harness/agent_surfaces/skills_sync.mjs`");
    process.exit(1);
  }
  console.log("skills in sync: .claude/skills matches .codex/skills");
  process.exit(0);
}
console.log(`done: ${written} generated, ${removed} stale removed, ${skipped} skipped`);
