/*
 * Build the Critter Corral sprite pack:
 *   critter_corral.ntpack -- sprite.vert + sprite.frag + atlas with 9 sprites
 *   (critter_a, critter_b, critter, pen, flag, grass, lure, spark, pip).
 *
 * The sprite shaders are the engine-shipped assets/shaders/sprite.{vert,frag}
 * (resolved via an asset root pointing at external/neotolis-engine so the
 * resource ids match the engine sprite-renderer shader contract). The sprite
 * PNGs are placeholders generated by tools/critter_corral/generate_sprites.py.
 *
 * RGBA, premultiplied alpha (NT_BLEND_MODE_ALPHA at runtime), LINEAR filter,
 * CLAMP_TO_EDGE, RECT shape (soft round blobs trim fine as rects).
 *
 * Usage: build_critter_corral_packs <pack_dir>
 * Run from the project root directory.
 */

#include "nt_builder.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef _WIN32
#include <direct.h>
#define MKDIR(p) _mkdir(p)
#else
#include <sys/stat.h>
#define MKDIR(p) mkdir(p, 0755)
#endif

#define HEADER_DIR "tools/critter_corral/generated"
#define ENGINE_ROOT "external/neotolis-engine"
#define SPRITE_SRC_DIR "gamedesign/projects/critter-corral/art/sprites"

static char s_path_buf[512];

static const char *pack_path(const char *dir, const char *name) {
    (void)snprintf(s_path_buf, sizeof(s_path_buf), "%s/%s", dir, name);
    return s_path_buf;
}

int main(int argc, char *argv[]) {
    if (argc < 2) {
        (void)fprintf(stderr, "Usage: build_critter_corral_packs <pack_dir>\n");
        return 1;
    }
    const char *out_dir = argv[1];

    (void)printf("=== Build Critter Corral Pack -> %s ===\n\n", out_dir);

    MKDIR(out_dir);
    MKDIR("tools/critter_corral/generated");

    char cache_dir[512];
    (void)snprintf(cache_dir, sizeof(cache_dir), "%s/_cache", out_dir);
    MKDIR(cache_dir);

    NtBuilderContext *ctx = nt_builder_start_pack(pack_path(out_dir, "critter_corral.ntpack"));
    if (!ctx) {
        (void)fprintf(stderr, "Failed to start critter_corral.ntpack\n");
        return 1;
    }

    nt_builder_set_header_dir(ctx, HEADER_DIR);
    nt_builder_set_cache_dir(ctx, cache_dir);
    /* Engine root so assets/shaders/sprite.* (and common/globals.glsl) resolve. */
    nt_builder_add_asset_root(ctx, ENGINE_ROOT);

    // NOLINTNEXTLINE(concurrency-mt-unsafe) -- single-threaded CLI tool, getenv is fine
    const char *threads_env = getenv("NT_BUILDER_THREADS");
    if (threads_env && threads_env[0] != '\0') {
        uint32_t threads = (uint32_t)strtoul(threads_env, NULL, 10);
        if (threads > 0) {
            nt_builder_set_threads(ctx, threads);
        } else {
            nt_builder_set_threads_auto(ctx);
        }
    } else {
        nt_builder_set_threads_auto(ctx);
    }

    // #region shaders (engine-shipped sprite pipeline)
    nt_builder_add_shader(ctx, "assets/shaders/sprite.vert", NT_BUILD_SHADER_VERTEX);
    nt_builder_add_shader(ctx, "assets/shaders/sprite.frag", NT_BUILD_SHADER_FRAGMENT);
    (void)printf("  Shaders added: sprite.vert + sprite.frag\n");
    // #endregion

    // #region atlas: 6 critter-corral sprites
    nt_atlas_opts_t atlas_opts = nt_atlas_opts_defaults();
    atlas_opts.shape = NT_ATLAS_SHAPE_RECT; /* soft round blobs trim fine as rects */
    atlas_opts.allow_transform = true;
    atlas_opts.pixels_per_unit = 1.0F; /* 1 source pixel = 1 world unit */
    atlas_opts.padding = 2;
    atlas_opts.margin = 2;
    atlas_opts.extrude = 2; /* valid with RECT */
    atlas_opts.premultiplied = true;
    /* Soft 2D illustration scaled down a bit: LINEAR, no mips, clamp. */
    atlas_opts.filter_min = NT_TEXTURE_DEFAULT_FILTER_LINEAR;
    atlas_opts.filter_mag = NT_TEXTURE_DEFAULT_FILTER_LINEAR;
    atlas_opts.wrap_u = NT_TEXTURE_DEFAULT_WRAP_CLAMP_TO_EDGE;
    atlas_opts.wrap_v = NT_TEXTURE_DEFAULT_WRAP_CLAMP_TO_EDGE;
    atlas_opts.gen_mipmaps = false;

    nt_builder_begin_atlas(ctx, "corral", &atlas_opts);

    /* Centre pivot for everything — matches the game's centre-based draw math. */
    nt_atlas_sprite_opts_t centre = nt_atlas_sprite_opts_defaults();

    nt_builder_atlas_add(ctx, SPRITE_SRC_DIR "/critter_a.png", &centre);
    nt_builder_atlas_add(ctx, SPRITE_SRC_DIR "/critter_b.png", &centre);
    nt_builder_atlas_add(ctx, SPRITE_SRC_DIR "/critter.png", &centre);
    nt_builder_atlas_add(ctx, SPRITE_SRC_DIR "/pen.png", &centre);
    nt_builder_atlas_add(ctx, SPRITE_SRC_DIR "/flag.png", &centre);
    nt_builder_atlas_add(ctx, SPRITE_SRC_DIR "/grass.png", &centre);
    nt_builder_atlas_add(ctx, SPRITE_SRC_DIR "/lure.png", &centre);
    nt_builder_atlas_add(ctx, SPRITE_SRC_DIR "/spark.png", &centre);
    nt_builder_atlas_add(ctx, SPRITE_SRC_DIR "/pip.png", &centre);

    nt_builder_end_atlas(ctx);
    (void)printf("  Atlas 'corral' added: 9 sprites (RECT, ppu=1.0)\n");
    // #endregion

    // #region finish + codegen
    nt_build_result_t r = nt_builder_finish_pack(ctx);
    nt_builder_free_pack(ctx);
    if (r != NT_BUILD_OK) {
        (void)fprintf(stderr, "critter_corral.ntpack failed: %d\n", r);
        return 1;
    }

    /* Rename the per-pack header to a stable combined name. */
    char base_hdr[512];
    (void)snprintf(base_hdr, sizeof(base_hdr), "%s/critter_corral.h", HEADER_DIR);
    const char *headers[] = {base_hdr};
    char combined[512];
    (void)snprintf(combined, sizeof(combined), "%s/critter_corral_assets.h", HEADER_DIR);
    nt_builder_merge_headers(headers, 1, combined);
    (void)printf("Generated: %s\n", combined);
    // #endregion

    /* Print pack size summary */
    (void)printf("\n=== Pack Size Summary ===\n");
    FILE *f = fopen(pack_path(out_dir, "critter_corral.ntpack"), "rb");
    if (f) {
        (void)fseek(f, 0, SEEK_END);
        long sz = ftell(f);
        (void)fclose(f);
        (void)printf("  critter_corral.ntpack    %8.1f KB\n", (double)sz / 1024.0);
    }

    (void)printf("\n=== Done ===\n");
    return 0;
}
