#!/usr/bin/env python3
# Convert Kenney Furniture Kit OBJ+MTL models (CC0) into a C header of per-material
# sub-meshes (position + index arrays + the material's Kd colour) for
# nt_shape_renderer_mesh. Each model is normalized once (centered on X/Z, sitting
# on the floor, uniformly scaled so X-width matches a target footprint), then split
# by material so the shape renderer draws each colour group separately.
# Usage: python tools/little-lives/obj_to_header.py
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "assets", "source", "models", "kenney", "furniture_kit")
OUT = os.path.join(ROOT, "src", "ll_meshes.h")

# (C macro, obj base name, target X-width in world units)
MODELS = [
    ("BED", "bedDouble", 2.6),
    ("FRIDGE", "kitchenFridge", 1.2),
    ("SHOWER", "shower", 1.4),
    ("TOILET", "toilet", 0.95),
    ("SOFA", "loungeSofa", 2.7),
    ("DESK", "desk", 1.7),
]


def parse_mtl(path):
    cols = {}
    cur = None
    for line in open(path, "r", encoding="utf-8", errors="ignore"):
        t = line.split()
        if not t:
            continue
        if t[0] == "newmtl":
            cur = t[1]
        elif t[0] == "Kd" and cur:
            cols[cur] = (float(t[1]), float(t[2]), float(t[3]))
    return cols


def parse_obj(path):
    verts = []
    groups = {}
    cur = "_default"
    for line in open(path, "r", encoding="utf-8", errors="ignore"):
        t = line.split()
        if not t:
            continue
        if t[0] == "v":
            verts.append((float(t[1]), float(t[2]), float(t[3])))
        elif t[0] == "usemtl":
            cur = t[1]
        elif t[0] == "f":
            idx = [int(tok.split("/")[0]) - 1 for tok in t[1:]]
            g = groups.setdefault(cur, [])
            for k in range(1, len(idx) - 1):
                g.append((idx[0], idx[k], idx[k + 1]))
    return verts, groups


def norm_fn(verts, target_w):
    xs = [v[0] for v in verts]
    ys = [v[1] for v in verts]
    zs = [v[2] for v in verts]
    cx = (min(xs) + max(xs)) * 0.5
    cz = (min(zs) + max(zs)) * 0.5
    miny = min(ys)
    s = target_w / ((max(xs) - min(xs)) or 1.0)
    return lambda v: ((v[0] - cx) * s, (v[1] - miny) * s, (v[2] - cz) * s)


def main():
    out = ["// Generated by tools/little-lives/obj_to_header.py from Kenney Furniture",
           "// Kit (CC0). Per-material sub-meshes for nt_shape_renderer_mesh.",
           "#ifndef LL_MESHES_H", "#define LL_MESHES_H", "#include <stdint.h>", "",
           "typedef struct { const float *pos; int nverts; const uint16_t *idx; int nidx; float r, g, b; } LLSub;",
           "typedef struct { const LLSub *subs; int nsubs; } LLMesh;", ""]
    table = []
    for macro, base, tw in MODELS:
        cols = parse_mtl(os.path.join(SRC, base + ".mtl"))
        verts, groups = parse_obj(os.path.join(SRC, base + ".obj"))
        tf = norm_fn(verts, tw)
        subs = []
        si = 0
        for mat, tris in groups.items():
            used = sorted({i for t in tris for i in t})
            remap = {gi: li for li, gi in enumerate(used)}
            pos = [c for gi in used for c in tf(verts[gi])]
            idx = [remap[i] for t in tris for i in t]
            assert len(used) < 65535, base
            r, g, b = cols.get(mat, (0.7, 0.7, 0.7))
            pn = "LL_%s_S%d" % (macro, si)
            out.append("static const float %s_POS[] = {%s};" % (pn, ", ".join("%.4ff" % v for v in pos)))
            out.append("static const uint16_t %s_IDX[] = {%s};" % (pn, ", ".join(str(i) for i in idx)))
            subs.append((pn, len(used), len(idx), r, g, b))
            si += 1
        out.append("static const LLSub LL_%s_SUBS[] = {" % macro)
        for pn, nv, ni, r, g, b in subs:
            out.append("    {%s_POS, %d, %s_IDX, %d, %.4ff, %.4ff, %.4ff}," % (pn, nv, pn, ni, r, g, b))
        out.append("};")
        out.append("")
        table.append((macro, len(subs)))
    out.append("enum { " + ", ".join("LL_MESH_%s" % m for m, _ in table) + ", LL_MESH_COUNT };")
    out.append("static const LLMesh LL_MESHES[LL_MESH_COUNT] = {")
    for macro, ns in table:
        out.append("    {LL_%s_SUBS, %d}," % (macro, ns))
    out.append("};")
    out.append("#endif")
    open(OUT, "w", encoding="utf-8").write("\n".join(out) + "\n")
    print("wrote", OUT)
    for macro, ns in table:
        print("  %-8s submeshes=%d" % (macro, ns))


if __name__ == "__main__":
    main()
