// Generate .claude/skills/* thin pointers from canonical .codex/skills/*.
// Single source of truth stays in .codex/skills; Claude Code discovers the
// same skills through generated pointer files. Re-run after adding or
// renaming a skill:
//
//   node tools/skills_sync.mjs
//
// Generated files carry a marker line; the script only overwrites files it
// generated, so a hand-written .claude skill is never clobbered.

import { mkdirSync, readdirSync, readFileSync, writeFileSync, existsSync, statSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const srcDir = join(root, ".codex", "skills");
const dstDir = join(root, ".claude", "skills");
const MARKER = "<!-- generated by tools/skills_sync.mjs; edit .codex/skills instead -->";

function parseFrontmatter(text) {
  const lines = text.split(/\r?\n/);
  if (lines[0] !== "---") return {};
  const end = lines.indexOf("---", 1);
  if (end === -1) return {};
  const fields = {};
  let current = null;
  for (const line of lines.slice(1, end)) {
    const m = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (m) {
      current = m[1];
      fields[current] = m[2].trim();
    } else if (current && /^\s+/.test(line)) {
      fields[current] += " " + line.trim();
    }
  }
  for (const k of Object.keys(fields)) {
    fields[k] = fields[k].replace(/^["']|["']$/g, "");
  }
  return fields;
}

function listReferences(skillDir) {
  const refDir = join(skillDir, "references");
  if (!existsSync(refDir)) return [];
  return readdirSync(refDir).filter((f) => f.endsWith(".md"));
}

if (!existsSync(srcDir)) {
  console.error(`error: ${srcDir} not found`);
  process.exit(1);
}

let written = 0;
let skipped = 0;
for (const name of readdirSync(srcDir)) {
  const skillDir = join(srcDir, name);
  const skillFile = join(skillDir, "SKILL.md");
  if (!statSync(skillDir).isDirectory() || !existsSync(skillFile)) continue;

  const fields = parseFrontmatter(readFileSync(skillFile, "utf8"));
  if (!fields.name || !fields.description) {
    console.warn(`warn: ${name}/SKILL.md missing name or description, skipped`);
    continue;
  }

  const outDir = join(dstDir, name);
  const outFile = join(outDir, "SKILL.md");
  if (existsSync(outFile) && !readFileSync(outFile, "utf8").includes(MARKER)) {
    console.log(`skip (hand-written): ${name}`);
    skipped++;
    continue;
  }

  const refs = listReferences(skillDir);
  const refLines = refs.length
    ? ["", "Reference playbooks (load only when the canonical skill says to):", "",
       ...refs.map((r) => `- \`.codex/skills/${name}/references/${r}\``)]
    : [];

  const body = [
    "---",
    `name: ${fields.name}`,
    `description: ${JSON.stringify(fields.description)}`,
    "---",
    MARKER,
    "",
    `# ${fields.name}`,
    "",
    `Canonical instructions live in \`.codex/skills/${name}/SKILL.md\` (single`,
    "source of truth shared by all agent CLIs). Read that file and follow it.",
    ...refLines,
    "",
  ].join("\n");

  mkdirSync(outDir, { recursive: true });
  writeFileSync(outFile, body);
  console.log(`generated: ${name}`);
  written++;
}
console.log(`done: ${written} generated, ${skipped} skipped`);
