import assert from "node:assert/strict";
import test from "node:test";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const marker = "<!-- generated by tools/skills_sync.mjs; edit .codex/skills instead -->";

function tempDir() {
  return mkdtempSync(join(tmpdir(), "skills-sync-test-"));
}

function cleanup(dir) {
  rmSync(dir, { recursive: true, force: true });
}

function run(args) {
  return spawnSync(process.execPath, ["tools/skills_sync.mjs", ...args], {
    cwd: root,
    encoding: "utf8",
    stdio: "pipe",
  });
}

function writeSkill(dir, name, description = "Use when testing skill sync.") {
  const skillDir = join(dir, ".codex", "skills", name);
  mkdirSync(skillDir, { recursive: true });
  writeFileSync(
    join(skillDir, "SKILL.md"),
    [
      "---",
      `name: ${name}`,
      `description: ${description}`,
      "---",
      "",
      `# ${name}`,
      "",
      "Canonical body.",
      "",
    ].join("\n"),
    "utf8",
  );
}

function writeClaudeSkill(dir, name, body) {
  const skillDir = join(dir, ".claude", "skills", name);
  mkdirSync(skillDir, { recursive: true });
  writeFileSync(join(skillDir, "SKILL.md"), body, "utf8");
}

test("skills sync generates thin pointers and check passes", () => {
  const dir = tempDir();
  try {
    writeSkill(dir, "sample");
    const generated = run(["--root", dir]);
    assert.equal(generated.status, 0, generated.stderr);
    assert.match(generated.stdout, /done: 1 generated, 0 stale removed, 0 skipped/);

    const out = readFileSync(join(dir, ".claude", "skills", "sample", "SKILL.md"), "utf8");
    assert.match(out, /Canonical instructions live in `.codex\/skills\/sample\/SKILL.md`/);

    const checked = run(["--root", dir, "--check"]);
    assert.equal(checked.status, 0, checked.stderr);
    assert.match(checked.stdout, /skills in sync/);
  } finally {
    cleanup(dir);
  }
});

test("skills sync check fails on stale generated pointers", () => {
  const dir = tempDir();
  try {
    writeSkill(dir, "sample");
    const generated = run(["--root", dir]);
    assert.equal(generated.status, 0, generated.stderr);

    writeClaudeSkill(dir, "old-skill", `${marker}\n# old-skill\n`);

    const checked = run(["--root", dir, "--check"]);
    assert.equal(checked.status, 1);
    assert.match(checked.stderr, /skills drift: 1 .*old-skill/);
    assert.ok(existsSync(join(dir, ".claude", "skills", "old-skill", "SKILL.md")));

    const fixed = run(["--root", dir]);
    assert.equal(fixed.status, 0, fixed.stderr);
    assert.match(fixed.stdout, /removed stale generated pointer: old-skill/);
    assert.equal(existsSync(join(dir, ".claude", "skills", "old-skill", "SKILL.md")), false);
  } finally {
    cleanup(dir);
  }
});

test("skills sync preserves hand-written claude skills", () => {
  const dir = tempDir();
  try {
    writeSkill(dir, "sample");
    writeClaudeSkill(dir, "manual", "# manual\n\nNo generated marker.\n");

    const synced = run(["--root", dir]);
    assert.equal(synced.status, 0, synced.stderr);
    assert.match(synced.stdout, /1 skipped/);
    assert.ok(existsSync(join(dir, ".claude", "skills", "manual", "SKILL.md")));

    const checked = run(["--root", dir, "--check"]);
    assert.equal(checked.status, 0, checked.stderr);
  } finally {
    cleanup(dir);
  }
});
