# A bare consumer's libcurl for network-core's native client: the studio's
# vendored curl (the engine's deps/curl), plain HTTP and WebSockets only, as
# the tests speak ws://. A game gets its curl from the engine instead
# (NT_HTTP_CURL + NT_HTTP_WEBSOCKETS).
set(NETWORK_CORE_TEST_CURL "${CMAKE_CURRENT_LIST_DIR}/../../../external/neotolis-engine/deps/curl")
block(SCOPE_FOR VARIABLES)
    set(BUILD_CURL_EXE OFF)
    set(BUILD_SHARED_LIBS OFF)
    set(BUILD_STATIC_LIBS ON)
    set(BUILD_EXAMPLES OFF)
    set(BUILD_TESTING OFF)
    set(BUILD_LIBCURL_DOCS OFF)
    set(BUILD_MISC_DOCS OFF)
    set(ENABLE_CURL_MANUAL OFF)
    set(CMAKE_DISABLE_FIND_PACKAGE_Perl ON)
    set(Perl_FOUND FALSE)
    set(PERL_FOUND FALSE)
    set(PERL_EXECUTABLE "")
    set(HTTP_ONLY OFF)
    foreach(protocol DICT FILE FTP GOPHER IMAP IPFS LDAP LDAPS MQTT POP3 RTSP SMTP TELNET TFTP)
        set(CURL_DISABLE_${protocol} ON)
    endforeach()
    set(CURL_DISABLE_WEBSOCKETS OFF)
    set(CURL_ENABLE_SSL OFF)
    set(CURL_USE_SCHANNEL OFF)
    set(CURL_USE_OPENSSL OFF)
    set(CURL_DISABLE_ALTSVC ON)
    set(CURL_DISABLE_HSTS ON)
    set(CURL_DISABLE_DOH ON)
    set(CURL_DISABLE_COOKIES ON)
    set(CURL_DISABLE_AWS ON)
    set(CURL_DISABLE_INSTALL ON)
    set(CURL_ENABLE_EXPORT_TARGET OFF)
    set(CURL_USE_LIBPSL OFF)
    set(CURL_USE_LIBSSH2 OFF)
    set(CURL_ZLIB OFF)
    set(CURL_BROTLI OFF)
    set(CURL_ZSTD OFF)
    set(USE_NGHTTP2 OFF)
    set(USE_LIBIDN2 OFF)
    add_subdirectory("${NETWORK_CORE_TEST_CURL}" "${CMAKE_BINARY_DIR}/_network_core_curl" EXCLUDE_FROM_ALL)
endblock()
set_property(GLOBAL PROPERTY NT_HTTP_WEBSOCKETS ON)
